/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexaobanco.ConexaoComBanco;
import dao.CanaisDAO;
import dao.CanalUserDAO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Canais;
import modelo.CanalUser;
import modelo.Secao;
import modelo.Usuario;

/**
 *
 * @author Rebeca
 */
public class TelaConfiguracoesAtivasUser extends JFrame {
    /**
     * Creates new form TelaConfiguraçõesAtivas
     */
    CanalUserDAO dao = new CanalUserDAO();
    DefaultTableModel dm = (DefaultTableModel) dao.User(0, 10);
    Connection con = null;
    Secao secaoUsu = new Secao();
    PreparedStatement ps = null;
    ResultSet rs = null;
    int indicePaginaCanaisUsu = 0;
    Usuario usuarioLogado = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    
    int paginaInicial = (int) dao.getRowCount();
    
    public TelaConfiguracoesAtivasUser(int idUsuario) {
        
        initComponents();
        ObterUsuario(idUsuario);
        atualizarTabelaUser();
        
        String sql = "SELECT email_user FROM secao where id_user = 1";
        con = new ConexaoComBanco().getConnection();

        try {
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                secaoUsu.setEmail_user(rs.getString("email_user"));
            }
        } catch (SQLException u) {
            throw new RuntimeException(u);
        }
        
        lbEmailPefilUsu.setText((String)secaoUsu.getEmail_user());
        
        
        restaurarDadosComboBoxCanais();

        //PAGINAÇÃO TABELA CANAIS
        /*tbDadosUser.setModel(dm);
        btnPrevUsu.setEnabled(false);
        btnStartUsu.setEnabled(false);*/

        if (paginaInicial <= 10) {
            btnNextUsu.setEnabled(false);
            btnEndUsu.setEnabled(false);
        }

        lbUsuario.setVisible(false);
        lbSenha.setVisible(false);
        txtUsuario.setVisible(false);
        txtSenha.setVisible(false);
        lbToken.setVisible(false);
        txtToken.setVisible(false);

    }
    
    public boolean ObterUsuario(int idUsuario) {
        Usuario usuario = usuarioDAO.obterUsuarioPorId(idUsuario);
        if (usuario != null) {
            this.usuarioLogado = usuario;
        return true;
        }else{
            return false;
        }
    }

    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(850, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height); 
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelTabelaAdm = new javax.swing.JPanel();
        campoBuscaUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDadosUser = new javax.swing.JTable();
        lbPesqui = new javax.swing.JLabel();
        painelNaveg2 = new javax.swing.JPanel();
        btnAtualizarTabelaUsu = new javax.swing.JButton();
        btnStartUsu = new javax.swing.JButton();
        btnNextUsu = new javax.swing.JButton();
        btnPrevUsu = new javax.swing.JButton();
        btnEndUsu = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();
        painelMenu = new jPanelGradient();
        lbLogo = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        lbEmailPefilUsu = new javax.swing.JLabel();
        PainelConfigAdm = new javax.swing.JPanel();
        lbNomeCanal = new javax.swing.JLabel();
        txtNomeCanalUser = new javax.swing.JTextField();
        cbNomeCanal = new javax.swing.JComboBox<>();
        lbPadraoAutenticacao = new javax.swing.JLabel();
        cbPadraoAutenticacao = new javax.swing.JComboBox<>();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lbToken = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        lbNomeCanal1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbBtnAdd = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbBtnEditar = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbBtnExcluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Sistema de autorização do Usuário");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTabelaAdm.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyTyped(evt);
            }
        });
        PainelTabelaAdm.add(campoBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 742, 30));

        tbDadosUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Canais", "Token", "Usuário", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDadosUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosUserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosUserMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDadosUser);

        PainelTabelaAdm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 860, 233));

        lbPesqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaAdm.add(lbPesqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 30, 30));

        painelNaveg2.setBackground(new java.awt.Color(232, 232, 232));

        btnAtualizarTabelaUsu.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabelaUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabelaUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabelaUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabelaUsu.setBorder(null);
        btnAtualizarTabelaUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabelaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaUsuActionPerformed(evt);
            }
        });

        btnStartUsu.setBackground(new java.awt.Color(217, 90, 48));
        btnStartUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStartUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnStartUsu.setText("Inicio");
        btnStartUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartUsuActionPerformed(evt);
            }
        });

        btnNextUsu.setBackground(new java.awt.Color(217, 90, 48));
        btnNextUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNextUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnNextUsu.setText(">>");
        btnNextUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextUsuMouseClicked(evt);
            }
        });
        btnNextUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextUsuActionPerformed(evt);
            }
        });

        btnPrevUsu.setBackground(new java.awt.Color(217, 90, 48));
        btnPrevUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrevUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevUsu.setText("<<");
        btnPrevUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevUsuMouseClicked(evt);
            }
        });
        btnPrevUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevUsuActionPerformed(evt);
            }
        });

        btnEndUsu.setBackground(new java.awt.Color(217, 90, 48));
        btnEndUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEndUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnEndUsu.setText("Fim");
        btnEndUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelNaveg2Layout = new javax.swing.GroupLayout(painelNaveg2);
        painelNaveg2.setLayout(painelNaveg2Layout);
        painelNaveg2Layout.setHorizontalGroup(
            painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNaveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrevUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAtualizarTabelaUsu)
                .addGap(12, 12, 12)
                .addComponent(btnNextUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEndUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        painelNaveg2Layout.setVerticalGroup(
            painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNaveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNextUsu)
                        .addComponent(btnEndUsu))
                    .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAtualizarTabelaUsu)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStartUsu)
                            .addComponent(btnPrevUsu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelTabelaAdm.add(painelNaveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 310, 40));

        jPanel1.add(PainelTabelaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 900, 340));

        lbTexto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbTexto.setText("<html> <body style=\"text-align:center\"> Olá, seja bem vindo! Aqui você pode visualizar, editar ou adicionar os canais cadastrados na <br>  tabela abaixo! </body> </html>");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 670, 50));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        lbPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconePerfil.png"))); // NOI18N
        lbPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPerfilMouseClicked(evt);
            }
        });

        lbEmailPefilUsu.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailPefilUsu.setText("Teste");

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 617, Short.MAX_VALUE)
                .addComponent(lbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmailPefilUsu)
                .addGap(66, 66, 66))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEmailPefilUsu)
                            .addComponent(lbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(painelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        PainelConfigAdm.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeCanal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCanal.setText("Canais Cadastrados:");
        PainelConfigAdm.add(lbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        txtNomeCanalUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCanalUserActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(txtNomeCanalUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 239, -1));

        cbNomeCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar..." }));
        cbNomeCanal.setBorder(null);
        cbNomeCanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNomeCanalMouseClicked(evt);
            }
        });
        cbNomeCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeCanalActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 147, -1));

        lbPadraoAutenticacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPadraoAutenticacao.setText("Padrão Autenticação :");
        PainelConfigAdm.add(lbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        cbPadraoAutenticacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Token", "Senha" }));
        cbPadraoAutenticacao.setBorder(null);
        cbPadraoAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPadraoAutenticacaoActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 147, -1));

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario.setText("Usuário:");
        PainelConfigAdm.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, -1));

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenha.setText("Senha:");
        PainelConfigAdm.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));
        PainelConfigAdm.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 130, -1));

        lbToken.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbToken.setText("Token:");
        PainelConfigAdm.add(lbToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));
        PainelConfigAdm.add(txtToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, -1));

        lbNomeCanal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCanal1.setText("Nome :");
        PainelConfigAdm.add(lbNomeCanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAdd.setText("ADICIONAR");
        lbBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 130, 30));

        jPanel6.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditar.setText("EDITAR");
        lbBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 130, -1));

        jPanel7.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluir.setText("EXCLUIR");
        lbBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 130, -1));

        jPanel1.add(PainelConfigAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 900, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesqActionPerformed

    private void cbNomeCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeCanalActionPerformed

    }//GEN-LAST:event_cbNomeCanalActionPerformed

    private void cbPadraoAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPadraoAutenticacaoActionPerformed
        // TODO add your handling code here:
        if (cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Token")) {
            //Define o Campo de Texto Token como visível
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setVisible(true);
            lbToken.setVisible(true);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
        } else if (cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Senha")) {
            //Define o Campo de Texto Senha como visível
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            lbUsuario.setVisible(true);
            txtUsuario.setVisible(true);
            txtSenha.setVisible(true);
            lbSenha.setVisible(true);
        } else {
            //Volta ao estado original 
            txtSenha.setText("");
            txtToken.setText("");
            txtUsuario.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
        }
    }//GEN-LAST:event_cbPadraoAutenticacaoActionPerformed

    private void tbDadosUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUser.getSelectedRow() != -1) {
            txtNomeCanalUser.setText(tbDadosUser.getValueAt(tbDadosUser.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbDadosUserMouseClicked

    private void campoBuscaUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canal_usuario WHERE nome_canal LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%" + campoBuscaUser.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDadosUser.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_usuario"),
                    rs.getString("nome_canal"),
                    rs.getString("token"),
                    rs.getString("usuario"),
                    rs.getString("senha"),});
            }
            rs.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaUserKeyTyped

    private void campoBuscaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserKeyPressed

    private void tbDadosUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosUserMousePressed

    private void txtNomeCanalUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCanalUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCanalUserActionPerformed

    private void cbNomeCanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNomeCanalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomeCanalMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lbBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirMouseClicked
        // Botão excluir:
        if (tbDadosUser.getSelectedRow() != -1) {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDadosUser.getSelectedRow();
            String cell = tbDadosUser.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM canal_usuario WHERE id_canal_usuario = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabelaUser();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        atualizarTabelaUser();
    }//GEN-LAST:event_lbBtnExcluirMouseClicked

    private void lbBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarMouseClicked
                

        if (tbDadosUser.getSelectedRow() != -1) {

            CanalUser user = new CanalUser();
            CanalUserDAO updateDAO = new CanalUserDAO();

            user.setNome_canal(txtNomeCanalUser.getText());
            user.setToken(txtToken.getText());
            user.setUsuario(txtUsuario.getText());
            user.setSenha(txtSenha.getText());
            user.setIdusuario((int) tbDadosUser.getValueAt(tbDadosUser.getSelectedRow(), 0));

            updateDAO.updateUser(user);

            txtNomeCanalUser.setText("");
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setText("");

            atualizarTabelaUser();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarMouseClicked

    private void lbBtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddMouseClicked
        // TODO add your handling code here:
        String nome_canal, token, usuario, senha;

        nome_canal = txtNomeCanalUser.getText();
        token = txtToken.getText();
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();

        CanalUser user = new CanalUser();
        user.setNome_canal(nome_canal);
        user.setToken(token);
        user.setUsuario(usuario);
        user.setSenha(senha);
        user.setIdusuario(usuarioLogado.getId_usuario());
        
        CanalUserDAO userDAO = new CanalUserDAO();
        userDAO.adicionaCanalUser(user);
        atualizarTabelaUser();
    }//GEN-LAST:event_lbBtnAddMouseClicked

    private void lbPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPerfilMouseClicked
        // TODO add your handling code here:
        TelaConfiguracoesConta telaConfigConta = new TelaConfiguracoesConta();
        telaConfigConta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPerfilMouseClicked

    private void btnAtualizarTabelaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaUsuActionPerformed
        // TODO add your handling code here:
        atualizarTabelaUser();
    }//GEN-LAST:event_btnAtualizarTabelaUsuActionPerformed

    private void btnStartUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartUsuActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(0, 10);
        tbDadosUser.setModel(pagina);
        btnStartUsu.setEnabled(false);
        btnPrevUsu.setEnabled(false);
        btnNextUsu.setEnabled(true);
        btnEndUsu.setEnabled(true);
        indicePaginaCanaisUsu = 0;
    }//GEN-LAST:event_btnStartUsuActionPerformed

    private void btnNextUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextUsuMouseClicked
        // TODO add your handling code here:
        indicePaginaCanaisUsu = indicePaginaCanaisUsu + 10;
    }//GEN-LAST:event_btnNextUsuMouseClicked

    private void btnNextUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextUsuActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();

        //(currentPage, totalPages);
        int index = (int) dao.getRowCount();
        int tamanho = indicePaginaCanaisUsu + 10;

        int resultado = index - tamanho;

        if (resultado < 10) {
            btnNextUsu.setEnabled(false);
            btnEndUsu.setEnabled(false);
        }

        if (tamanho == 0) {
            btnPrevUsu.setEnabled(false);
            btnStartUsu.setEnabled(false);
        } else {
            btnPrevUsu.setEnabled(true);
            btnStartUsu.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDadosUser.setModel(pagina);
    }//GEN-LAST:event_btnNextUsuActionPerformed

    private void btnPrevUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevUsuMouseClicked
        // TODO add your handling code here:
        
        indicePaginaCanaisUsu = indicePaginaCanaisUsu - 10;
    }//GEN-LAST:event_btnPrevUsuMouseClicked

    private void btnPrevUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevUsuActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        //(currentPage, totalPages);

        int tamanho = indicePaginaCanaisUsu - 10;

        btnNextUsu.setEnabled(true);
        btnEndUsu.setEnabled(true);

        if (tamanho == 0) {
            btnPrevUsu.setEnabled(false);
            btnStartUsu.setEnabled(false);
        } else {
            btnPrevUsu.setEnabled(true);
            btnStartUsu.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDadosUser.setModel(pagina);
    }//GEN-LAST:event_btnPrevUsuActionPerformed

    private void btnEndUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndUsuActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        int index = (int) dao.getRowCount();

        int valorfinal = index / 10;
        int valortotal = valorfinal * 10;
        System.out.println(valorfinal);
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(valortotal, 10);
        tbDadosUser.setModel(pagina);
        btnNextUsu.setEnabled(false);
        btnEndUsu.setEnabled(false);
        btnStartUsu.setEnabled(true);
        btnPrevUsu.setEnabled(true);
        indicePaginaCanaisUsu = valortotal;
    }//GEN-LAST:event_btnEndUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesAtivasUser(0).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfigAdm;
    private javax.swing.JPanel PainelTabelaAdm;
    private javax.swing.JButton btnAtualizarTabelaUsu;
    private javax.swing.JButton btnEndUsu;
    private javax.swing.JButton btnNextUsu;
    private javax.swing.JButton btnPrevUsu;
    private javax.swing.JButton btnStartUsu;
    private javax.swing.JTextField campoBuscaUser;
    private javax.swing.JComboBox<String> cbNomeCanal;
    private javax.swing.JComboBox<String> cbPadraoAutenticacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBtnAdd;
    private javax.swing.JLabel lbBtnEditar;
    private javax.swing.JLabel lbBtnExcluir;
    private javax.swing.JLabel lbEmailPefilUsu;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCanal;
    private javax.swing.JLabel lbNomeCanal1;
    private javax.swing.JLabel lbPadraoAutenticacao;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbPesqui;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbToken;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelNaveg2;
    private javax.swing.JTable tbDadosUser;
    private javax.swing.JTextField txtNomeCanalUser;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabelaUser() {

        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canal_usuario WHERE id_usuario = ? LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setInt(1, usuarioLogado.getId_usuario());
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDadosUser.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
            int idxxx = rs.getInt("id_usuario");
                modelo.addRow(new Object[]{rs.getInt("id_canal_usuario"),
                    rs.getString("nome_canal"),
                    rs.getString("token"),
                    rs.getString("usuario"),
                    rs.getString("senha")
                });
            }
            rs.close();
            connection.close();
            indicePaginaCanaisUsu = 0;
            btnStartUsu.setEnabled(false);
            btnPrevUsu.setEnabled(false);

            if (paginaInicial <= 10) {
                btnNextUsu.setEnabled(false);
                btnEndUsu.setEnabled(false);
            } else {
                btnNextUsu.setEnabled(true);
                btnEndUsu.setEnabled(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }           

    }
    Vector<String> nome_canal = new Vector<String>();

    public void restaurarDadosComboBoxCanais() {
        try {
            CanaisDAO cnl = new CanaisDAO();
            ResultSet rs = cnl.listarCanal();

            while (rs.next()) {
                //nome_canal.addElement(rs.getInt(1));
                cbNomeCanal.addItem(rs.getString(1));
            }
        } catch (SQLException erro) {
            System.out.println(erro.getMessage());
        }
    }
}