/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.CanalUserDAO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import modelo.Canais;
import modelo.CanalUser;
import modelo.Secao;

/**
 *
 * @author fatec
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    Usuario usuarioLogado = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();

    public TelaCadastro() {
        initComponents();
        btnEsconderSenha.setVisible(false);
        btnEsconderConfirm.setVisible(false);
    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipalCadastro = new jPanelGradient();
        painelCadastro = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        lbConfirmSenha = new javax.swing.JLabel();
        lbTextoCadastro = new javax.swing.JLabel();
        painelBtnCadastrar = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JLabel();
        btnVoltarLogin = new javax.swing.JLabel();
        iconeNome = new javax.swing.JLabel();
        iconeEmail = new javax.swing.JLabel();
        iconeSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEsconderSenha = new javax.swing.JButton();
        btnMostrarSenha = new javax.swing.JButton();
        txtConfirmSenha = new javax.swing.JPasswordField();
        btnEsconderConfirm = new javax.swing.JButton();
        btnMostrarConfirm = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Cadastro");
        setResizable(false);

        painelCadastro.setBackground(new java.awt.Color(249, 250, 251));
        painelCadastro.setPreferredSize(new java.awt.Dimension(400, 520));

        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 51, 51));
        lbNome.setText("Nome:");

        lbEmail.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("E-mail:");

        lbSenha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(51, 51, 51));
        lbSenha.setText("Senha:");

        lbConfirmSenha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbConfirmSenha.setForeground(new java.awt.Color(51, 51, 51));
        lbConfirmSenha.setText("Confirmar senha:");

        lbTextoCadastro.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        lbTextoCadastro.setForeground(new java.awt.Color(200, 88, 51));
        lbTextoCadastro.setText("<html>\n<body style=\"text-align:center\">\n<p>REALIZAR</p>\n<p style=\"color:#30124E\">CADASTRO</p>\n</body>\n</html>");

        painelBtnCadastrar.setBackground(new java.awt.Color(200, 88, 51));
        painelBtnCadastrar.setPreferredSize(new java.awt.Dimension(211, 36));

        btnCadastrar.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnCadastrarLayout = new javax.swing.GroupLayout(painelBtnCadastrar);
        painelBtnCadastrar.setLayout(painelBtnCadastrarLayout);
        painelBtnCadastrarLayout.setHorizontalGroup(
            painelBtnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );
        painelBtnCadastrarLayout.setVerticalGroup(
            painelBtnCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnVoltarLogin.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        btnVoltarLogin.setForeground(new java.awt.Color(48, 18, 78));
        btnVoltarLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVoltarLogin.setText("Já tem uma conta?");
        btnVoltarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarLoginMouseClicked(evt);
            }
        });

        iconeNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeUsuario.png"))); // NOI18N

        iconeEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeEmail.png"))); // NOI18N

        iconeSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeSenha.png"))); // NOI18N

        btnEsconderSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoFechado.png"))); // NOI18N
        btnEsconderSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconderSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderSenhaActionPerformed(evt);
            }
        });

        btnMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoAberto.png"))); // NOI18N
        btnMostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSenhaActionPerformed(evt);
            }
        });

        txtConfirmSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmSenhaActionPerformed(evt);
            }
        });

        btnEsconderConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoFechado.png"))); // NOI18N
        btnEsconderConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconderConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderConfirmActionPerformed(evt);
            }
        });

        btnMostrarConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoAberto.png"))); // NOI18N
        btnMostrarConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbTextoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbNome))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(iconeNome)
                        .addGap(6, 6, 6)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbEmail))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(iconeEmail)
                        .addGap(6, 6, 6)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbSenha))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(iconeSenha)
                        .addGap(6, 6, 6)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarSenha)
                            .addComponent(btnEsconderSenha)))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(painelBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnVoltarLogin))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbConfirmSenha)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(txtConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMostrarConfirm)
                                    .addComponent(btnEsconderConfirm))))))
                .addGap(52, 52, 52))
        );

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtConfirmSenha, txtEmail, txtNome, txtSenha});

        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbTextoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbNome)
                .addGap(2, 2, 2)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lbEmail)
                .addGap(2, 2, 2)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lbSenha)
                .addGap(2, 2, 2)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarSenha)
                            .addComponent(btnEsconderSenha)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(lbConfirmSenha)
                .addGap(10, 10, 10)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarConfirm)
                    .addComponent(btnEsconderConfirm))
                .addGap(30, 30, 30)
                .addComponent(painelBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarLogin)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtConfirmSenha, txtEmail, txtNome, txtSenha});

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        javax.swing.GroupLayout painelPrincipalCadastroLayout = new javax.swing.GroupLayout(painelPrincipalCadastro);
        painelPrincipalCadastro.setLayout(painelPrincipalCadastroLayout);
        painelPrincipalCadastroLayout.setHorizontalGroup(
            painelPrincipalCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo)
                .addGap(102, 102, 102)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        painelPrincipalCadastroLayout.setVerticalGroup(
            painelPrincipalCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalCadastroLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        Usuario usuario = new Usuario();
        UsuarioDAO daousu = new UsuarioDAO();

        if (txtNome.getText().isEmpty() || txtEmail.getText().isEmpty() || txtSenha.getText().isEmpty() || txtConfirmSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        } else {
            usuario.setNome_usuario(txtNome.getText());
            usuario.setEmail_usuario(txtEmail.getText());

            if (txtSenha.getText().equals(txtConfirmSenha.getText())) {
                usuario.setSenha_usuario(txtSenha.getText());
                daousu.adicionaUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuario " + txtNome.getText() + " Cadastrado com sucesso !");
                new TelaLogin().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "As senhas não estão iguais !");
            }
        }
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnVoltarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarLoginMouseClicked
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarLoginMouseClicked

    private void btnEsconderSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderSenhaActionPerformed
        txtSenha.setEchoChar('*'); // Com echo char, é possível definir um caractere que aparecerá sempre que um usuário digitar a senha no JPasswordField.
        btnMostrarSenha.setVisible(true);
        btnEsconderSenha.setVisible(false);
    }//GEN-LAST:event_btnEsconderSenhaActionPerformed

    private void btnMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSenhaActionPerformed
        txtSenha.setEchoChar('\u0000'); //Aqui é onde definimos o JPassoword para colocar a senha vísivel. Um char tem um valor padrão de 'u0000'.
        btnMostrarSenha.setVisible(false);
        btnEsconderSenha.setVisible(true);
    }//GEN-LAST:event_btnMostrarSenhaActionPerformed

    private void btnMostrarConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarConfirmActionPerformed
        txtConfirmSenha.setEchoChar('\u0000'); //Aqui é onde definimos o JPassoword para colocar a senha vísivel. Um char tem um valor padrão de 'u0000'.
        btnMostrarConfirm.setVisible(false);
        btnEsconderConfirm.setVisible(true);
    }//GEN-LAST:event_btnMostrarConfirmActionPerformed

    private void btnEsconderConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderConfirmActionPerformed
        txtConfirmSenha.setEchoChar('*'); // Com echo char, é possível definir um caractere que aparecerá sempre que um usuário digitar a senha no JPasswordField.
        btnMostrarConfirm.setVisible(true);
        btnEsconderConfirm.setVisible(false);
    }//GEN-LAST:event_btnEsconderConfirmActionPerformed

    private void txtConfirmSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastrar;
    private javax.swing.JButton btnEsconderConfirm;
    private javax.swing.JButton btnEsconderSenha;
    private javax.swing.JButton btnMostrarConfirm;
    private javax.swing.JButton btnMostrarSenha;
    private javax.swing.JLabel btnVoltarLogin;
    private javax.swing.JLabel iconeEmail;
    private javax.swing.JLabel iconeNome;
    private javax.swing.JLabel iconeSenha;
    private javax.swing.JLabel lbConfirmSenha;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTextoCadastro;
    private javax.swing.JPanel painelBtnCadastrar;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelPrincipalCadastro;
    private javax.swing.JPasswordField txtConfirmSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
