/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexãobanco.ConexaoComBanco;
import dao.CanaisDAO;
import dao.CanalUserDAO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Canais;
import modelo.CanalUser;
import modelo.Usuario;

/**
 *
 * @author Rebeca
 */
public class TelaConfiguracoesAtivasUser extends JFrame {

    /**
     * Creates new form TelaConfiguraçõesAtivas
     */
    CanalUserDAO dao = new CanalUserDAO();
    DefaultTableModel dm = (DefaultTableModel) dao.User(0, 10);

    int indexAbas = 1;
    int indicePaginaCanais = 0;

    int paginaInicial = (int) dao.getRowCount();

    public TelaConfiguracoesAtivasUser() {
        initComponents();
        atualizarTabelaUser();
        restaurarDadosComboBoxCanais();

        //PAGINAÇÃO TABELA CANAIS
        tbDadosUser.setModel(dm);
        lbBtnPrev.setEnabled(false);
        lbBtnInicio.setEnabled(false);

        if (paginaInicial <= 10) {
            lbBtnNext.setEnabled(false);
            lbBtnFim.setEnabled(false);
        }

        lbUsuario.setVisible(false);
        lbSenha.setVisible(false);
        txtUsuario.setVisible(false);
        txtSenha.setVisible(false);
        lbToken.setVisible(false);
        txtToken.setVisible(false);

    }

    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(850, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height); 
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelTabelaAdm = new javax.swing.JPanel();
        campoBuscaUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDadosUser = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAtualizarTabela = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lbBtnFim = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbBtnNext = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbBtnPrev = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbBtnInicio = new javax.swing.JLabel();
        lbPesqui = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        painelMenu = new jPanelGradient();
        lbLogo = new javax.swing.JLabel();
        lbPerfil = new javax.swing.JLabel();
        PainelConfigAdm = new javax.swing.JPanel();
        lbNomeCanal = new javax.swing.JLabel();
        txtNomeCanalUser = new javax.swing.JTextField();
        cbNomeCanal = new javax.swing.JComboBox<>();
        lbPadraoAutenticacao = new javax.swing.JLabel();
        cbPadraoAutenticacao = new javax.swing.JComboBox<>();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lbToken = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        lbNomeCanal1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbBtnAdd = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbBtnEditar = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbBtnExcluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Sistema de autorização do Usuário");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelTabelaAdm.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyTyped(evt);
            }
        });
        PainelTabelaAdm.add(campoBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 742, 30));

        tbDadosUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Canais", "Token", "Usuário", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDadosUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosUserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosUserMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDadosUser);

        PainelTabelaAdm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 860, 233));

        jPanel4.setBackground(new java.awt.Color(232, 232, 232));

        btnAtualizarTabela.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabela.setBorder(null);
        btnAtualizarTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnFim.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnFim.setText("Fim");
        lbBtnFim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnFim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnFimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnFim, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnFim, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnNext.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnNext.setText(">>");
        lbBtnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnPrev.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnPrev.setText("<<");
        lbBtnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnPrevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnInicio.setText("Início");
        lbBtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTabela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelTabelaAdm.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 290, 330, -1));

        lbPesqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaAdm.add(lbPesqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 30, 30));

        jPanel1.add(PainelTabelaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 900, 340));

        lbTexto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbTexto.setText("<html> <body style=\"text-align:center\"> Olá, seja bem vindo! Aqui você pode visualizar, editar ou adicionar os canais cadastrados na <br>  tabela abaixo! </body> </html>");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 670, 50));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        lbPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconePerfil.png"))); // NOI18N
        lbPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPerfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                .addComponent(lbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(painelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        PainelConfigAdm.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeCanal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCanal.setText("Canais Cadastrados:");
        PainelConfigAdm.add(lbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        txtNomeCanalUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCanalUserActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(txtNomeCanalUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 239, -1));

        cbNomeCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar..." }));
        cbNomeCanal.setBorder(null);
        cbNomeCanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNomeCanalMouseClicked(evt);
            }
        });
        cbNomeCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeCanalActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 147, -1));

        lbPadraoAutenticacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPadraoAutenticacao.setText("Padrão Autenticação :");
        PainelConfigAdm.add(lbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        cbPadraoAutenticacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Token", "Senha" }));
        cbPadraoAutenticacao.setBorder(null);
        cbPadraoAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPadraoAutenticacaoActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 147, -1));

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario.setText("Usuário:");
        PainelConfigAdm.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, -1));

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenha.setText("Senha:");
        PainelConfigAdm.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));
        PainelConfigAdm.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 130, -1));

        lbToken.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbToken.setText("Token:");
        PainelConfigAdm.add(lbToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));
        PainelConfigAdm.add(txtToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, -1));

        lbNomeCanal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCanal1.setText("Nome :");
        PainelConfigAdm.add(lbNomeCanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel5.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAdd.setText("ADICIONAR");
        lbBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 130, 30));

        jPanel6.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditar.setText("EDITAR");
        lbBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 130, -1));

        jPanel7.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluir.setText("EXCLUIR");
        lbBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelConfigAdm.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 130, -1));

        jPanel1.add(PainelConfigAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 900, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesqActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // Botão atualizar tabela:
        atualizarTabelaUser();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void cbNomeCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeCanalActionPerformed

    }//GEN-LAST:event_cbNomeCanalActionPerformed

    private void cbPadraoAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPadraoAutenticacaoActionPerformed
        // TODO add your handling code here:
        if (cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Token")) {
            //Define o Campo de Texto Token como visível
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setVisible(true);
            lbToken.setVisible(true);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
        } else if (cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Senha")) {
            //Define o Campo de Texto Senha como visível
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            lbUsuario.setVisible(true);
            txtUsuario.setVisible(true);
            txtSenha.setVisible(true);
            lbSenha.setVisible(true);
        } else {
            //Volta ao estado original 
            txtSenha.setText("");
            txtToken.setText("");
            txtUsuario.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
        }
    }//GEN-LAST:event_cbPadraoAutenticacaoActionPerformed

    private void tbDadosUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUser.getSelectedRow() != -1) {
            txtNomeCanalUser.setText(tbDadosUser.getValueAt(tbDadosUser.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbDadosUserMouseClicked

    private void campoBuscaUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canal_usuario WHERE nome_canal LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%" + campoBuscaUser.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDadosUser.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_usuario"),
                    rs.getString("nome_canal"),
                    rs.getString("token"),
                    rs.getString("usuario"),
                    rs.getString("senha"),});
            }
            rs.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaUserKeyTyped

    private void campoBuscaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserKeyPressed

    private void tbDadosUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUserMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosUserMousePressed

    private void txtNomeCanalUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCanalUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCanalUserActionPerformed

    private void cbNomeCanalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNomeCanalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomeCanalMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lbBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirMouseClicked
        // Botão excluir:
        if (tbDadosUser.getSelectedRow() != -1) {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDadosUser.getSelectedRow();
            String cell = tbDadosUser.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM canal_usuario WHERE id_canal_usuario = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabelaUser();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        atualizarTabelaUser();
    }//GEN-LAST:event_lbBtnExcluirMouseClicked

    private void lbBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarMouseClicked
                //Botão de Atualizar dados dados da Tabela

        if (tbDadosUser.getSelectedRow() != -1) {

            CanalUser user = new CanalUser();
            CanalUserDAO updateDAO = new CanalUserDAO();

            user.setNome_canal(txtNomeCanalUser.getText());
            user.setToken(txtToken.getText());
            user.setUsuario(txtUsuario.getText());
            user.setSenha(txtSenha.getText());
            user.setIdusuario((int) tbDadosUser.getValueAt(tbDadosUser.getSelectedRow(), 0));

            updateDAO.updateUser(user);

            txtNomeCanalUser.setText("");
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setText("");

            atualizarTabelaUser();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarMouseClicked

    private void lbBtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddMouseClicked
        // TODO add your handling code here:
        String nome_canal, token, usuario, senha;

        nome_canal = txtNomeCanalUser.getText();
        token = txtToken.getText();
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();

        CanalUser user = new CanalUser();
        user.setNome_canal(nome_canal);
        user.setToken(token);
        user.setUsuario(usuario);
        user.setSenha(senha);

        CanalUserDAO userDAO = new CanalUserDAO();
        userDAO.adicionaCanalUser(user);
        atualizarTabelaUser();
    }//GEN-LAST:event_lbBtnAddMouseClicked

    private void lbBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnInicioMouseClicked
    // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(0, 10);
        tbDadosUser.setModel(pagina);
        lbBtnInicio.setEnabled(false);
        lbBtnPrev.setEnabled(false);
        lbBtnNext.setEnabled(true);
        lbBtnFim.setEnabled(true);
        indicePaginaCanais = 0;
    }//GEN-LAST:event_lbBtnInicioMouseClicked

    private void lbBtnFimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnFimMouseClicked
        // TODO add your handling code here:

        CanaisDAO dao = new CanaisDAO();
        int index = (int) dao.getRowCount();

        int valorfinal = index / 10;
        int valortotal = valorfinal * 10;
        System.out.println(valorfinal);
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(valortotal, 10);
        tbDadosUser.setModel(pagina);
        lbBtnNext.setEnabled(false);
        lbBtnFim.setEnabled(false);
        lbBtnInicio.setEnabled(true);
        lbBtnPrev.setEnabled(true);
        indicePaginaCanais = valortotal;

    }//GEN-LAST:event_lbBtnFimMouseClicked

    private void lbBtnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnPrevMouseClicked
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        //(currentPage, totalPages);

        int tamanho = indicePaginaCanais - 10;

        lbBtnNext.setEnabled(true);
        lbBtnFim.setEnabled(true);

        if (tamanho == 0) {
            lbBtnPrev.setEnabled(false);
            lbBtnInicio.setEnabled(false);
        } else {
            lbBtnPrev.setEnabled(true);
            lbBtnInicio.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDadosUser.setModel(pagina);

    }//GEN-LAST:event_lbBtnPrevMouseClicked

    private void lbBtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnNextMouseClicked
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();

        //(currentPage, totalPages);
        int index = (int) dao.getRowCount();
        int tamanho = indicePaginaCanais + 10;

        int resultado = index - tamanho;

        if (resultado < 10) {
            lbBtnNext.setEnabled(false);
            lbBtnFim.setEnabled(false);
        }

        if (tamanho == 0) {
            lbBtnPrev.setEnabled(false);
            lbBtnInicio.setEnabled(false);
        } else {
            lbBtnPrev.setEnabled(true);
            lbBtnInicio.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDadosUser.setModel(pagina);
    }//GEN-LAST:event_lbBtnNextMouseClicked

    private void lbPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPerfilMouseClicked
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbPerfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesAtivasUser().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfigAdm;
    private javax.swing.JPanel PainelTabelaAdm;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JTextField campoBuscaUser;
    private javax.swing.JComboBox<String> cbNomeCanal;
    private javax.swing.JComboBox<String> cbPadraoAutenticacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBtnAdd;
    private javax.swing.JLabel lbBtnEditar;
    private javax.swing.JLabel lbBtnExcluir;
    private javax.swing.JLabel lbBtnFim;
    private javax.swing.JLabel lbBtnInicio;
    private javax.swing.JLabel lbBtnNext;
    private javax.swing.JLabel lbBtnPrev;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCanal;
    private javax.swing.JLabel lbNomeCanal1;
    private javax.swing.JLabel lbPadraoAutenticacao;
    private javax.swing.JLabel lbPerfil;
    private javax.swing.JLabel lbPesqui;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbToken;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JTable tbDadosUser;
    private javax.swing.JTextField txtNomeCanalUser;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabelaUser() {

        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canal_usuario LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDadosUser.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_canal_usuario"),
                    rs.getString("nome_canal"),
                    rs.getString("token"),
                    rs.getString("usuario"),
                    rs.getString("senha")
                });
            }
            rs.close();
            connection.close();
            indicePaginaCanais = 0;
            lbBtnInicio.setEnabled(false);
            lbBtnPrev.setEnabled(false);

            if (paginaInicial <= 10) {
                lbBtnNext.setEnabled(false);
                lbBtnFim.setEnabled(false);
            } else {
                lbBtnNext.setEnabled(true);
                lbBtnFim.setEnabled(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    Vector<String> nome_canal = new Vector<String>();

    public void restaurarDadosComboBoxCanais() {
        try {
            CanaisDAO cnl = new CanaisDAO();
            ResultSet rs = cnl.listarCanal();

            while (rs.next()) {
                //nome_canal.addElement(rs.getInt(1));
                cbNomeCanal.addItem(rs.getString(1));
            }
        } catch (SQLException erro) {
            System.out.println(erro.getMessage());
        }
    }
}