/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexãobanco.ConexaoComBanco;
import dao.CanaisDAO;
import java.awt.ComponentOrientation;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Canais;

/**
 *
 * @author Rebeca
 */
public class TelaConfiguracoesAtivas extends JFrame {

    /**
     * Creates new form TelaConfiguraçõesAtivas
     */
    CanaisDAO dao = new CanaisDAO();
    DefaultTableModel dm = (DefaultTableModel) dao.fetchBySize(0, 10);
    int pagesnext = 0;
    
    public TelaConfiguracoesAtivas(){
        initComponents();
        atualizarTabela();
        tbDados.setModel(dm);
        btnPrev.setEnabled(false);
        btnStart.setEnabled(false);
        //Desabilita Campos de Texto de Token e Senha até que sejam selecionados
        txtToken.setVisible(false);
        lbToken.setVisible(false);
        txtSenha.setVisible(false);
        lbSenha.setVisible(false);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnAtualizarTabela = new javax.swing.JButton();
        lbPesqui = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbNomeCanal = new javax.swing.JLabel();
        txtNomeCanal = new javax.swing.JTextField();
        lbTipoCanal = new javax.swing.JLabel();
        cbTipoCanal = new javax.swing.JComboBox<>();
        lbPadraoAutenticacao = new javax.swing.JLabel();
        cbPadraoAutenticacao = new javax.swing.JComboBox<>();
        txtToken = new javax.swing.JTextField();
        lbToken = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lbAdicionar = new javax.swing.JLabel();
        lbEditar = new javax.swing.JLabel();
        lbExcluir = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de autorização");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pesquisar por nome:");

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesqActionPerformed(evt);
            }
        });
        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaKeyTyped(evt);
            }
        });

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Canais", "Tipo", "Padão de Autentificação", "Token", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDados);

        btnStart.setText("Start");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStartMouseReleased(evt);
            }
        });
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPrev.setText("<<");
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        btnPrev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPrevKeyPressed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnEnd.setText("End");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        btnAtualizarTabela.setBackground(new java.awt.Color(255, 153, 51));
        btnAtualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AtualizarIcone2.png"))); // NOI18N
        btnAtualizarTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtualizarTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizarTabela)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStart)
                        .addComponent(btnPrev)
                        .addComponent(btnNext)
                        .addComponent(btnEnd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbPesqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PesquisarIcone.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbPesqui, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoBusca))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPesqui, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbNomeCanal.setText("Nome :");

        lbTipoCanal.setText("Tipo :");

        cbTipoCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MarketPlace", "PlataformaERP", "Forma de Pagamento" }));
        cbTipoCanal.setBorder(null);
        cbTipoCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCanalActionPerformed(evt);
            }
        });

        lbPadraoAutenticacao.setText("Padrão Autenticação :");

        cbPadraoAutenticacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Token", "Senha" }));
        cbPadraoAutenticacao.setBorder(null);
        cbPadraoAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPadraoAutenticacaoActionPerformed(evt);
            }
        });

        txtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenActionPerformed(evt);
            }
        });

        lbToken.setText("Token : ");

        lbSenha.setText("Senha : ");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(255, 153, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADICIONAR");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 153, 51));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEditar.setMaximumSize(new java.awt.Dimension(96, 22));
        btnEditar.setMinimumSize(new java.awt.Dimension(96, 22));
        btnEditar.setPreferredSize(new java.awt.Dimension(96, 22));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 153, 51));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR ");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnExcluir.setMaximumSize(new java.awt.Dimension(96, 22));
        btnExcluir.setMinimumSize(new java.awt.Dimension(96, 22));
        btnExcluir.setPreferredSize(new java.awt.Dimension(96, 22));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lbAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SalvarIcone.png"))); // NOI18N

        lbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditarIcone.png"))); // NOI18N

        lbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ExcluirIcone.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNomeCanal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCanal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTipoCanal)
                            .addComponent(lbPadraoAutenticacao))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPadraoAutenticacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSenha)
                    .addComponent(lbToken))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomeCanal)
                            .addComponent(txtNomeCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbToken)
                            .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTipoCanal)
                            .addComponent(cbTipoCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPadraoAutenticacao)
                            .addComponent(cbPadraoAutenticacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSenha)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnRetornar.setBackground(new java.awt.Color(255, 153, 51));
        btnRetornar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetornar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetornar.setText("Voltar");
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Olá, seja bem vindo! Aqui você pode visualizar os canais cadastrados na tabela abaixo e");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("as opções de adicionar ou editar canais.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRetornar)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnRetornar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesqActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // Botão atualizar tabela:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        new TelaCadastroCanais().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void cbTipoCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCanalActionPerformed

    private void cbPadraoAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPadraoAutenticacaoActionPerformed
        // TODO add your handling code here:
        if(cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Token")){
            //Define o Campo de Texto Token como visível
            txtSenha.setText("");
            txtToken.setVisible(true);
            lbToken.setVisible(true);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
        }
        else if(cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Senha")){
            //Define o Campo de Texto Senha como visível
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(true);
            lbSenha.setVisible(true);
        }
        else {
            //Volta ao estado original 
            txtSenha.setText("");
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
        }
    }//GEN-LAST:event_cbPadraoAutenticacaoActionPerformed

    private void txtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTokenActionPerformed

    private void tbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMouseClicked
        // TODO add your handling code here:
        if(tbDados.getSelectedRow()!= -1){
            
            txtNomeCanal.setText(tbDados.getValueAt(tbDados.getSelectedRow(), 1).toString());
            
            if(tbDados.getValueAt(tbDados.getSelectedRow(), 4)== null || tbDados.getValueAt(tbDados.getSelectedRow(), 4).equals("")){
                txtToken.setText("VAZIO");
                
            }else if(tbDados.getValueAt(tbDados.getSelectedRow(), 4)!= null & (tbDados.getValueAt(tbDados.getSelectedRow(), 5)== null || tbDados.getValueAt(tbDados.getSelectedRow(), 5).equals(""))){
                txtToken.setText(tbDados.getValueAt(tbDados.getSelectedRow(), 4).toString());
                txtSenha.setText("VAZIO");
            }
            
            if(tbDados.getValueAt(tbDados.getSelectedRow(), 5)== null || tbDados.getValueAt(tbDados.getSelectedRow(), 5).equals("")){
                txtSenha.setText("VAZIO");
                
            }else if(tbDados.getValueAt(tbDados.getSelectedRow(), 5)!= null & (tbDados.getValueAt(tbDados.getSelectedRow(), 4)== null || tbDados.getValueAt(tbDados.getSelectedRow(), 4).equals(""))){
                txtSenha.setText(tbDados.getValueAt(tbDados.getSelectedRow(), 5).toString());
                txtToken.setText("VAZIO");
            }
        }
    }//GEN-LAST:event_tbDadosMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();

        //(currentPage, totalPages);
        int index = (int)dao.getRowCount();
        int tamanho = pagesnext+10;
        
        int resultado = index - tamanho;
        
        if(resultado < 10){
            btnNext.setEnabled(false);
            btnEnd.setEnabled(false);
        }
        
        if(tamanho == 0){
            btnPrev.setEnabled(false);
            btnStart.setEnabled(false);
        }else{
            btnPrev.setEnabled(true);
            btnStart.setEnabled(true);  
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);    
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();
        //(currentPage, totalPages);
        
        int tamanho = pagesnext-10;
        
        btnNext.setEnabled(true);
        btnEnd.setEnabled(true);
        
        if(tamanho == 0){
            btnPrev.setEnabled(false);
            btnStart.setEnabled(false);
        }else{
            btnPrev.setEnabled(true);
            btnStart.setEnabled(true);  
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);
        
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(0, 10);
        tbDados.setModel(pagina);
        btnStart.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(true);
        btnEnd.setEnabled(true);
        pagesnext = 0;
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:
        
          CanaisDAO dao = new CanaisDAO();
          int index = (int) dao.getRowCount();
          
          int tamanho = index-10;
          int valorfinal = index/10;
          int valortotal = valorfinal*10;
          System.out.println(valorfinal);
          DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(valortotal, 10);
          tbDados.setModel(pagina);
          btnNext.setEnabled(false);
          btnEnd.setEnabled(false);
          btnStart.setEnabled(true);
          btnPrev.setEnabled(true);
          pagesnext = valortotal;
          
    }//GEN-LAST:event_btnEndActionPerformed

    private void campoBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM canais WHERE nome_canal LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%"+campoBusca.getText()+"%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDados.getModel();
            modelo.setNumRows(0);
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id_canais"),
                                               rs.getString("nome_canal"),
                                               rs.getString("tipo_canal"),
                                               rs.getString("padrao_autenticacao"),
                                               rs.getString("token"),
                                               rs.getString("senha_canal")
                                               });
                }
                rs.close();
                connection.close();
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaKeyTyped

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        pagesnext = pagesnext+10;
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnPrevKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPrevKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevKeyPressed

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        pagesnext = pagesnext-10;
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartMouseReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Botão de Atualizar dados dados da Tabela

        if (tbDados.getSelectedRow()!= -1){

            Canais canais = new Canais();
            CanaisDAO dao = new CanaisDAO();

            canais.setIdcanal((int) tbDados.getValueAt(tbDados.getSelectedRow(), 0));
            canais.setNomecanal(txtNomeCanal.getText());
            canais.setTipocanal(cbTipoCanal.getItemAt(cbTipoCanal.getSelectedIndex()));
            canais.setPadraoautenticacao(cbPadraoAutenticacao.getItemAt(cbPadraoAutenticacao.getSelectedIndex()));
            canais.setToken(txtToken.getText());
            canais.setSenhacanal(txtSenha.getText());

            dao.update(canais);

            txtNomeCanal.setText("");
            txtToken.setText("");
            txtSenha.setText("");

            atualizarTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Botão excluir:
        if (tbDados.getSelectedRow()!= -1){
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDados.getSelectedRow();
            String cell = tbDados.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM canais WHERE id_canais = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabela();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        atualizarTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();

        if((txtNomeCanal.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        }else{

            canais.setNomecanal(txtNomeCanal.getText());

            int indexTipoCanal = cbTipoCanal.getSelectedIndex();
            int indexPadrao = cbPadraoAutenticacao.getSelectedIndex();

            if (indexTipoCanal == 0){
                canais.setTipocanal("MarketPlace");
            }else if(indexTipoCanal == 1){
                canais.setTipocanal("Plataforma ERP");
            }else if(indexTipoCanal == 2){
                canais.setTipocanal("Forma de Pagamento");
            }
            if (indexPadrao == 0){
                canais.setPadraoautenticacao("Token");
            }else if(indexPadrao == 1){
                canais.setPadraoautenticacao("Senha");
            }

            canais.setSenhacanal(txtSenha.getText());
            canais.setToken(txtToken.getText());

            if(dao.saveusu(canais)){
                JOptionPane.showMessageDialog(null, "Canal "+txtNomeCanal.getText()+" Cadastrado com sucesso !");
            }else{
                JOptionPane.showMessageDialog(null,"Ops ! Algo deu errado, tente novamente.");
            }
        }
        txtNomeCanal.setText("");
        txtSenha.setText("");
        txtToken.setText("");
        atualizarTabela();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tbDadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosMousePressed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesAtivas().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JButton btnStart;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JComboBox<String> cbPadraoAutenticacao;
    private javax.swing.JComboBox<String> cbTipoCanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAdicionar;
    private javax.swing.JLabel lbEditar;
    private javax.swing.JLabel lbExcluir;
    private javax.swing.JLabel lbNomeCanal;
    private javax.swing.JLabel lbPadraoAutenticacao;
    private javax.swing.JLabel lbPesqui;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTipoCanal;
    private javax.swing.JLabel lbToken;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField txtNomeCanal;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtToken;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {
        
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM canais LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel)tbDados.getModel();
            modelo.setNumRows(0);
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id_canais"),
                                               rs.getString("nome_canal"),
                                               rs.getString("tipo_canal"),
                                               rs.getString("padrao_autenticacao"),
                                               rs.getString("token"),
                                               rs.getString("senha_canal")
                                                });
                }
            rs.close();
            connection.close();
            pagesnext = 0;
            btnStart.setEnabled(false);
            btnPrev.setEnabled(false);
            btnNext.setEnabled(true);
            btnEnd.setEnabled(true);
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
