/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexãobanco.ConexaoComBanco;
import dao.CanaisDAO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Canais;
import modelo.Usuario;

/**
 *
 * @author Rebeca
 */
public class TelaConfiguracoesAtivas extends JFrame {

    /**
     * Creates new form TelaConfiguraçõesAtivas
     */
    CanaisDAO dao = new CanaisDAO();
    UsuarioDAO daoUsu = new UsuarioDAO();
    DefaultTableModel dm = (DefaultTableModel) dao.fetchBySize(0, 10);
    DefaultTableModel dmusu = (DefaultTableModel) daoUsu.fetchBySizeUsu(0, 10);
    
    int indexAbas = 1;
    int indicePaginaCanais = 0;
    int indicePaginaUsuario = 0;
    
    int paginaInicial = (int) dao.getRowCount();
    int paginaInicialUsu = (int) daoUsu.getRowCountUsu();
    
    
    public TelaConfiguracoesAtivas(){
        initComponents();
        atualizarTabela();
        
        //PAGINAÇÃO TABELA CANAIS
        tbDados.setModel(dm);
        lbBtnPrev.setEnabled(false);
        lbBtnInicio.setEnabled(false);
        
        if (paginaInicial <= 10){
            lbBtnNext.setEnabled(false);
            lbBtnFim.setEnabled(false);
        }
        //PAGINAÇÃO TABELA USUARIO
        tbDadosUsu.setModel(dmusu);
        lbBtnPrev1.setEnabled(false);
        lbBtnInicio1.setEnabled(false);
        
        if (paginaInicialUsu <= 10){
            lbBtnNext1.setEnabled(false);
            lbBtnFim1.setEnabled(false);
        }
        
        //GUIA DE ABAS
        PainelTabelaUsers.setVisible(false);
        PainelConfigUser.setVisible(false);
        
        if(indexAbas%2 != 0){
            PainelTabelaAdm.setVisible(true);
            PainelConfigAdm.setVisible(true);
            btnPaginaCanais.setEnabled(false);
        }
        
        //Campos de Texto Invisíveis 
        lbUsuario.setVisible(false);
        lbSenha.setVisible(false);
        txtUsuario.setVisible(false);
        txtSenha.setVisible(false);
        lbToken.setVisible(false);
        txtToken.setVisible(false);
        
}
    class jPanelGradient extends JPanel {
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(850, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height); 
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new jPanelGradient();
        lbLogo = new javax.swing.JLabel();
        lbBtnPerfil = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        painelFundo = new javax.swing.JPanel();
        btnPaginaCanais = new javax.swing.JLabel();
        btnPaginaUsuario = new javax.swing.JLabel();
        PainelTabelaUsers = new javax.swing.JPanel();
        campoBuscaUser = new javax.swing.JTextField();
        jScrollPaneTabelaUser = new javax.swing.JScrollPane();
        tbDadosUsu = new javax.swing.JTable();
        painelNavegUser = new javax.swing.JPanel();
        painelBtnIni1 = new javax.swing.JPanel();
        lbBtnInicio1 = new javax.swing.JLabel();
        painelBtnPrev1 = new javax.swing.JPanel();
        lbBtnPrev1 = new javax.swing.JLabel();
        painelBtnNext1 = new javax.swing.JPanel();
        lbBtnNext1 = new javax.swing.JLabel();
        painelBtnFim1 = new javax.swing.JPanel();
        lbBtnFim1 = new javax.swing.JLabel();
        btnAtualizarTabela1 = new javax.swing.JButton();
        lbPesquiUser1 = new javax.swing.JLabel();
        PainelTabelaAdm = new javax.swing.JPanel();
        campoBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        painelNaveg = new javax.swing.JPanel();
        btnAtualizarTabela = new javax.swing.JButton();
        painelBtnIni = new javax.swing.JPanel();
        lbBtnInicio = new javax.swing.JLabel();
        painelBtnPrev = new javax.swing.JPanel();
        lbBtnPrev = new javax.swing.JLabel();
        painelBtnNext = new javax.swing.JPanel();
        lbBtnNext = new javax.swing.JLabel();
        painelBtnFim = new javax.swing.JPanel();
        lbBtnFim = new javax.swing.JLabel();
        lbPesquiUser2 = new javax.swing.JLabel();
        PainelConfigUser = new javax.swing.JPanel();
        lbNomeUser = new javax.swing.JLabel();
        txtNomeUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbSenhaUser = new javax.swing.JLabel();
        txtSenhaUser = new javax.swing.JTextField();
        painelBotoesUser = new javax.swing.JPanel();
        painelBtnAddUser = new javax.swing.JPanel();
        lbBtnAddUser = new javax.swing.JLabel();
        painelBtnEditarUser = new javax.swing.JPanel();
        lbBtnEditarUser = new javax.swing.JLabel();
        painelBtnExcluirUser = new javax.swing.JPanel();
        lbBtnExcluirUser = new javax.swing.JLabel();
        PainelConfigAdm = new javax.swing.JPanel();
        lbNomeCanal = new javax.swing.JLabel();
        txtNomeCanal = new javax.swing.JTextField();
        lbTipoCanal = new javax.swing.JLabel();
        cbTipoCanal = new javax.swing.JComboBox<>();
        lbPadraoAutenticacao = new javax.swing.JLabel();
        cbPadraoAutenticacao = new javax.swing.JComboBox<>();
        txtSenha = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        lbToken = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        painelBtnAdd = new javax.swing.JPanel();
        lbBtnAdd = new javax.swing.JLabel();
        painelBtnEditar = new javax.swing.JPanel();
        lbBtnEditar = new javax.swing.JLabel();
        painelBtnExcluir = new javax.swing.JPanel();
        lbBtnExcluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Sistema de autorização");
        setResizable(false);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        lbBtnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconePerfil.png"))); // NOI18N
        lbBtnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnPerfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 695, Short.MAX_VALUE)
                .addComponent(lbBtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lbBtnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        lbTexto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbTexto.setText("<html>\n<body style=\"text-align:center\">\nOlá, seja bem vindo! Aqui você pode visualizar, editar ou adicionar os canais cadastrados na\n<br>\n tabela abaixo!\n</body>\n</html>");

        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPaginaCanais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeTabelaCanais.png"))); // NOI18N
        btnPaginaCanais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaginaCanais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaginaCanaisMouseClicked(evt);
            }
        });
        painelFundo.add(btnPaginaCanais, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnPaginaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeTabelaUsers.png"))); // NOI18N
        btnPaginaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaginaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaginaUsuarioMouseClicked(evt);
            }
        });
        painelFundo.add(btnPaginaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        PainelTabelaUsers.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaUserjTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyTyped(evt);
            }
        });
        PainelTabelaUsers.add(campoBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 740, 30));

        tbDadosUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDadosUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosUsuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosUsuMousePressed(evt);
            }
        });
        jScrollPaneTabelaUser.setViewportView(tbDadosUsu);

        PainelTabelaUsers.add(jScrollPaneTabelaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 233));

        painelNavegUser.setBackground(new java.awt.Color(232, 232, 232));

        painelBtnIni1.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnInicio1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnInicio1.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnInicio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnInicio1.setText("Início");
        lbBtnInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnInicio1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnIni1Layout = new javax.swing.GroupLayout(painelBtnIni1);
        painelBtnIni1.setLayout(painelBtnIni1Layout);
        painelBtnIni1Layout.setHorizontalGroup(
            painelBtnIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnIni1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnIni1Layout.setVerticalGroup(
            painelBtnIni1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnIni1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnPrev1.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnPrev1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnPrev1.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnPrev1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnPrev1.setText("<<");
        lbBtnPrev1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnPrev1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnPrev1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnPrev1Layout = new javax.swing.GroupLayout(painelBtnPrev1);
        painelBtnPrev1.setLayout(painelBtnPrev1Layout);
        painelBtnPrev1Layout.setHorizontalGroup(
            painelBtnPrev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnPrev1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        painelBtnPrev1Layout.setVerticalGroup(
            painelBtnPrev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnPrev1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        painelBtnNext1.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnNext1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnNext1.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnNext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnNext1.setText(">>");
        lbBtnNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnNext1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnNext1Layout = new javax.swing.GroupLayout(painelBtnNext1);
        painelBtnNext1.setLayout(painelBtnNext1Layout);
        painelBtnNext1Layout.setHorizontalGroup(
            painelBtnNext1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnNext1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnNext1Layout.setVerticalGroup(
            painelBtnNext1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnNext1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnFim1.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnFim1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnFim1.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnFim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnFim1.setText("Fim");
        lbBtnFim1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnFim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnFim1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnFim1Layout = new javax.swing.GroupLayout(painelBtnFim1);
        painelBtnFim1.setLayout(painelBtnFim1Layout);
        painelBtnFim1Layout.setHorizontalGroup(
            painelBtnFim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnFim1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnFim1Layout.setVerticalGroup(
            painelBtnFim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnFim1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnFim1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAtualizarTabela1.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabela1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabela1.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabela1.setBorder(null);
        btnAtualizarTabela1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabela1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelNavegUserLayout = new javax.swing.GroupLayout(painelNavegUser);
        painelNavegUser.setLayout(painelNavegUserLayout);
        painelNavegUserLayout.setHorizontalGroup(
            painelNavegUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegUserLayout.createSequentialGroup()
                .addComponent(painelBtnIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAtualizarTabela1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNavegUserLayout.setVerticalGroup(
            painelNavegUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNavegUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBtnFim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBtnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBtnIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTabela1)
                    .addComponent(painelBtnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelTabelaUsers.add(painelNavegUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 310, 30));

        lbPesquiUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaUsers.add(lbPesquiUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        painelFundo.add(PainelTabelaUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 880, 340));

        PainelTabelaAdm.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesqActionPerformed(evt);
            }
        });
        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaKeyTyped(evt);
            }
        });
        PainelTabelaAdm.add(campoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 742, 30));

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Canais", "Tipo", "Padão de Autentificação", "Token", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDados);

        PainelTabelaAdm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 233));

        painelNaveg.setBackground(new java.awt.Color(232, 232, 232));

        btnAtualizarTabela.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabela.setBorder(null);
        btnAtualizarTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });

        painelBtnIni.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnInicio.setText("Início");
        lbBtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnIniLayout = new javax.swing.GroupLayout(painelBtnIni);
        painelBtnIni.setLayout(painelBtnIniLayout);
        painelBtnIniLayout.setHorizontalGroup(
            painelBtnIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnIniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnIniLayout.setVerticalGroup(
            painelBtnIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnIniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnPrev.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnPrev.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnPrev.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnPrev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnPrev.setText("<<");
        lbBtnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnPrevMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnPrevLayout = new javax.swing.GroupLayout(painelBtnPrev);
        painelBtnPrev.setLayout(painelBtnPrevLayout);
        painelBtnPrevLayout.setHorizontalGroup(
            painelBtnPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnPrevLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnPrevLayout.setVerticalGroup(
            painelBtnPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnPrevLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnNext.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnNext.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnNext.setText(">>");
        lbBtnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnNextLayout = new javax.swing.GroupLayout(painelBtnNext);
        painelBtnNext.setLayout(painelBtnNextLayout);
        painelBtnNextLayout.setHorizontalGroup(
            painelBtnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnNextLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnNextLayout.setVerticalGroup(
            painelBtnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnNextLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnFim.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnFim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbBtnFim.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnFim.setText("Fim");
        lbBtnFim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnFim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnFimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnFimLayout = new javax.swing.GroupLayout(painelBtnFim);
        painelBtnFim.setLayout(painelBtnFimLayout);
        painelBtnFimLayout.setHorizontalGroup(
            painelBtnFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnFimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnFim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnFimLayout.setVerticalGroup(
            painelBtnFimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnFimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnFim, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelNavegLayout = new javax.swing.GroupLayout(painelNaveg);
        painelNaveg.setLayout(painelNavegLayout);
        painelNavegLayout.setHorizontalGroup(
            painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegLayout.createSequentialGroup()
                .addComponent(painelBtnIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizarTabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBtnFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNavegLayout.setVerticalGroup(
            painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBtnFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBtnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBtnIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarTabela))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelTabelaAdm.add(painelNaveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 310, 30));

        lbPesquiUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaAdm.add(lbPesquiUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        painelFundo.add(PainelTabelaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 40, 880, 340));

        PainelConfigUser.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeUser.setText("Nome :");
        PainelConfigUser.add(lbNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));
        PainelConfigUser.add(txtNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, 239, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        PainelConfigUser.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 152, -1));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEmail.setText("E-mail : ");
        PainelConfigUser.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lbSenhaUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenhaUser.setText("Senha : ");
        PainelConfigUser.add(lbSenhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        txtSenhaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUserActionPerformed(evt);
            }
        });
        PainelConfigUser.add(txtSenhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 147, -1));

        painelBotoesUser.setBackground(new java.awt.Color(249, 250, 251));

        painelBtnAddUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAddUser.setText("ADICIONAR");
        lbBtnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnAddUserLayout = new javax.swing.GroupLayout(painelBtnAddUser);
        painelBtnAddUser.setLayout(painelBtnAddUserLayout);
        painelBtnAddUserLayout.setHorizontalGroup(
            painelBtnAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBtnAddUserLayout.setVerticalGroup(
            painelBtnAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        painelBtnEditarUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditarUser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnEditarUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditarUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditarUser.setText("EDITAR");
        lbBtnEditarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnEditarUserLayout = new javax.swing.GroupLayout(painelBtnEditarUser);
        painelBtnEditarUser.setLayout(painelBtnEditarUserLayout);
        painelBtnEditarUserLayout.setHorizontalGroup(
            painelBtnEditarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnEditarUserLayout.setVerticalGroup(
            painelBtnEditarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnExcluirUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluirUser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnExcluirUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluirUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluirUser.setText("EXCLUIR");
        lbBtnExcluirUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluirUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnExcluirUserLayout = new javax.swing.GroupLayout(painelBtnExcluirUser);
        painelBtnExcluirUser.setLayout(painelBtnExcluirUserLayout);
        painelBtnExcluirUserLayout.setHorizontalGroup(
            painelBtnExcluirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBtnExcluirUserLayout.createSequentialGroup()
                .addComponent(lbBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBtnExcluirUserLayout.setVerticalGroup(
            painelBtnExcluirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnExcluirUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelBotoesUserLayout = new javax.swing.GroupLayout(painelBotoesUser);
        painelBotoesUser.setLayout(painelBotoesUserLayout);
        painelBotoesUserLayout.setHorizontalGroup(
            painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelBtnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnEditarUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnExcluirUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesUserLayout.setVerticalGroup(
            painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelConfigUser.add(painelBotoesUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 140, -1));

        painelFundo.add(PainelConfigUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 880, -1));

        PainelConfigAdm.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeCanal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNomeCanal.setText("Nome :");
        PainelConfigAdm.add(lbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        PainelConfigAdm.add(txtNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 239, -1));

        lbTipoCanal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTipoCanal.setText("Tipo :");
        PainelConfigAdm.add(lbTipoCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        cbTipoCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MarketPlace", "PlataformaERP", "Forma de Pagamento" }));
        cbTipoCanal.setBorder(null);
        cbTipoCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCanalActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbTipoCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 147, -1));

        lbPadraoAutenticacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbPadraoAutenticacao.setText("Padrão Autenticação :");
        PainelConfigAdm.add(lbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        cbPadraoAutenticacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Token", "Senha" }));
        cbPadraoAutenticacao.setBorder(null);
        cbPadraoAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPadraoAutenticacaoActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 147, -1));
        PainelConfigAdm.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 130, -1));

        lbSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbSenha.setText("Senha:");
        PainelConfigAdm.add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, -1));

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbUsuario.setText("Usuário:");
        PainelConfigAdm.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));
        PainelConfigAdm.add(txtToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, -1));

        lbToken.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbToken.setText("Token:");
        PainelConfigAdm.add(lbToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        painelBotoes.setBackground(new java.awt.Color(249, 250, 251));

        painelBtnAdd.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAdd.setText("ADICIONAR");
        lbBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnAddLayout = new javax.swing.GroupLayout(painelBtnAdd);
        painelBtnAdd.setLayout(painelBtnAddLayout);
        painelBtnAddLayout.setHorizontalGroup(
            painelBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBtnAddLayout.setVerticalGroup(
            painelBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        painelBtnEditar.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditar.setText("EDITAR");
        lbBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnEditarLayout = new javax.swing.GroupLayout(painelBtnEditar);
        painelBtnEditar.setLayout(painelBtnEditarLayout);
        painelBtnEditarLayout.setHorizontalGroup(
            painelBtnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnEditarLayout.setVerticalGroup(
            painelBtnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnExcluir.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluir.setText("EXCLUIR");
        lbBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnExcluirLayout = new javax.swing.GroupLayout(painelBtnExcluir);
        painelBtnExcluir.setLayout(painelBtnExcluirLayout);
        painelBtnExcluirLayout.setHorizontalGroup(
            painelBtnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBtnExcluirLayout.createSequentialGroup()
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBtnExcluirLayout.setVerticalGroup(
            painelBtnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnExcluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelConfigAdm.add(painelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        painelFundo.add(PainelConfigAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 880, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesqActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // Botão atualizar tabela:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void cbTipoCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCanalActionPerformed

    private void cbPadraoAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPadraoAutenticacaoActionPerformed
        // TODO add your handling code here:
if(cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Token")){
            //Define o Campo de Texto Token como visível
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setVisible(true);
            lbToken.setVisible(true);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
        }
        else if(cbPadraoAutenticacao.getSelectedItem().toString().equalsIgnoreCase("Senha")){
            //Define o Campo de Texto Senha como visível
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(true);
            lbSenha.setVisible(true);
            lbUsuario.setVisible(true);
            txtUsuario.setVisible(true);
        }
        else {
            //Volta ao estado original 
            txtSenha.setText("");
            txtUsuario.setText("");
            txtToken.setText("");
            txtToken.setVisible(false);
            lbToken.setVisible(false);
            txtSenha.setVisible(false);
            lbSenha.setVisible(false);
            lbUsuario.setVisible(false);
            txtUsuario.setVisible(false);
            
        }
    }//GEN-LAST:event_cbPadraoAutenticacaoActionPerformed

    private void tbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMouseClicked
        // TODO add your handling code here:
        if(tbDados.getSelectedRow()!= -1){ 
            txtNomeCanal.setText(tbDados.getValueAt(tbDados.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbDadosMouseClicked

    private void campoBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM canais WHERE nome_canal LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%"+campoBusca.getText()+"%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDados.getModel();
            modelo.setNumRows(0);
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id_canais"),
                                               rs.getString("nome_canal"),
                                               rs.getString("tipo_canal"),
                                               rs.getString("padrao_autenticacao"),
                                               rs.getString("token"),
                                               rs.getString("senha_canal")
                                               });
                }
                rs.close();
                connection.close();
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaKeyTyped

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void tbDadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosMousePressed

    private void campoBuscaUserjTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaUserjTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserjTextField_pesqActionPerformed

    private void campoBuscaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserKeyPressed

    private void campoBuscaUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM usuario WHERE nome_usuario LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%"+campoBuscaUser.getText()+"%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modeloUsu = (DefaultTableModel) tbDadosUsu.getModel();
            modeloUsu.setNumRows(0);
                while (rs.next()) {
                    modeloUsu.addRow(new Object[]{rs.getInt("id_usuario"),
                                               rs.getString("email_usuario"),
                                               rs.getString("nome_usuario"),
                                               rs.getString("senha_usuario"),
                                               });
                }
                rs.close();
                connection.close();
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaUserKeyTyped

    private void tbDadosUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUsuMouseClicked
        // TODO add your handling code here:
        if(tbDados.getSelectedRow()!= -1){ 
            txtNomeUser.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 1).toString());
            txtEmail.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 2).toString());
            txtSenhaUser.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbDadosUsuMouseClicked

    private void tbDadosUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUsuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosUsuMousePressed

    private void btnAtualizarTabela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabela1ActionPerformed
        // TODO add your handling code here:
        atualizarTabelaUsu();
    }//GEN-LAST:event_btnAtualizarTabela1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSenhaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUserActionPerformed

    private void btnPaginaCanaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaginaCanaisMouseClicked
        // TODO add your handling code here:
        indexAbas = indexAbas + 1;
        if(indexAbas%2 != 0){
            PainelTabelaAdm.setVisible(true);
            PainelConfigAdm.setVisible(true);
            PainelTabelaUsers.setVisible(false);
            PainelConfigUser.setVisible(false);
            
            btnPaginaCanais.setEnabled(false);
            btnPaginaUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_btnPaginaCanaisMouseClicked

    private void btnPaginaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaginaUsuarioMouseClicked
        // TODO add your handling code here:
        indexAbas = indexAbas + 1;
        if(indexAbas%2 == 0){
            PainelTabelaUsers.setVisible(true);
            PainelConfigUser.setVisible(true);
            PainelTabelaAdm.setVisible(false);
            PainelConfigAdm.setVisible(false);
            
            btnPaginaUsuario.setEnabled(false);
            btnPaginaCanais.setEnabled(true);
        }
    }//GEN-LAST:event_btnPaginaUsuarioMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lbBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnInicioMouseClicked
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(0, 10);
        tbDados.setModel(pagina);
        lbBtnInicio.setEnabled(false);
        lbBtnPrev.setEnabled(false);
        lbBtnNext.setEnabled(true);
        lbBtnFim.setEnabled(true);
        indicePaginaCanais = 0;
    }//GEN-LAST:event_lbBtnInicioMouseClicked

    private void lbBtnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnPrevMouseClicked
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        //(currentPage, totalPages);
        
        int tamanho = indicePaginaCanais-10;
        
        lbBtnNext.setEnabled(true);
        lbBtnFim.setEnabled(true);
        
        if(tamanho == 0){
            lbBtnPrev.setEnabled(false);
            lbBtnInicio.setEnabled(false);
        }else{
            lbBtnPrev.setEnabled(true);
            lbBtnInicio.setEnabled(true);  
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);
        
    }//GEN-LAST:event_lbBtnPrevMouseClicked

    private void lbBtnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnNextMouseClicked
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();

        //(currentPage, totalPages);
        int index = (int)dao.getRowCount();
        int tamanho = indicePaginaCanais+10;
        
        int resultado = index - tamanho;
        
        if(resultado < 10){
            lbBtnNext.setEnabled(false);
            lbBtnFim.setEnabled(false);
        }
        
        if(tamanho == 0){
            lbBtnPrev.setEnabled(false);
            lbBtnInicio.setEnabled(false);
        }else{
            lbBtnPrev.setEnabled(true);
            lbBtnInicio.setEnabled(true);  
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);
    }//GEN-LAST:event_lbBtnNextMouseClicked

    private void lbBtnFimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnFimMouseClicked
        // TODO add your handling code here:
        
          CanaisDAO dao = new CanaisDAO();
          int index = (int) dao.getRowCount();
          
          int valorfinal = index/10;
          int valortotal = valorfinal*10;
          System.out.println(valorfinal);
          DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(valortotal, 10);
          tbDados.setModel(pagina);
          lbBtnNext.setEnabled(false);
          lbBtnFim.setEnabled(false);
          lbBtnInicio.setEnabled(true);
          lbBtnPrev.setEnabled(true);
          indicePaginaCanais = valortotal;
    }//GEN-LAST:event_lbBtnFimMouseClicked

    private void lbBtnInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnInicio1MouseClicked
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(0, 10);
        
        tbDadosUsu.setModel(paginaUsu);
        lbBtnInicio1.setEnabled(false);
        lbBtnPrev1.setEnabled(false);
        lbBtnNext1.setEnabled(true);
        lbBtnFim1.setEnabled(true);
        indicePaginaUsuario = 0;
    }//GEN-LAST:event_lbBtnInicio1MouseClicked

    private void lbBtnPrev1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnPrev1MouseClicked
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        //(currentPage, totalPages);
        
        int tamanhoUsu = indicePaginaUsuario-10;
        
        lbBtnNext1.setEnabled(true);
        lbBtnFim1.setEnabled(true);
        
        if(tamanhoUsu == 0){
            lbBtnPrev1.setEnabled(false);
            lbBtnInicio1.setEnabled(false);
        }else{
            lbBtnPrev1.setEnabled(true);
            lbBtnInicio1.setEnabled(true);  
        }
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(tamanhoUsu, 10);
        tbDadosUsu.setModel(paginaUsu);
    }//GEN-LAST:event_lbBtnPrev1MouseClicked

    private void lbBtnNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnNext1MouseClicked
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();

        //(currentPage, totalPages);
        int index = (int)daoUsu.getRowCountUsu();
        int tamanhoUsu = indicePaginaUsuario+10;
        
        int resultado = index - tamanhoUsu;
        
        if(resultado < 10){
            lbBtnNext1.setEnabled(false);
            lbBtnFim1.setEnabled(false);
        }
        
        if(tamanhoUsu == 0){
            lbBtnPrev1.setEnabled(false);
            lbBtnInicio1.setEnabled(false);
        }else{
            lbBtnPrev1.setEnabled(true);
            lbBtnInicio1.setEnabled(true);  
        }
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(tamanhoUsu, 10);
        tbDadosUsu.setModel(paginaUsu);  
    }//GEN-LAST:event_lbBtnNext1MouseClicked

    private void lbBtnFim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnFim1MouseClicked
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        int indexTbUsu = (int) daoUsu.getRowCountUsu();
          
        int valorfinal = indexTbUsu/10;
        int valortotal = valorfinal*10;
        System.out.println(valorfinal);
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(valortotal, 10);
        tbDadosUsu.setModel(paginaUsu);
        lbBtnNext1.setEnabled(false);
        lbBtnFim1.setEnabled(false);
        lbBtnInicio1.setEnabled(true);
        lbBtnPrev1.setEnabled(true);
        indicePaginaUsuario = valortotal;
    }//GEN-LAST:event_lbBtnFim1MouseClicked

    private void lbBtnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddUserMouseClicked
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        UsuarioDAO daoUsu = new UsuarioDAO();
        
        if(txtNomeUser.getText().isEmpty()||txtEmail.getText().isEmpty()||txtSenhaUser.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        }else{
            usuario.setNome_usuario(txtNomeUser.getText());
            usuario.setEmail_usuario(txtEmail.getText());
            usuario.setSenha_usuario(txtSenhaUser.getText());
            daoUsu.adicionaUsuario(usuario);
            JOptionPane.showMessageDialog(null, "Usuario "+txtNomeUser.getText()+" Cadastrado com sucesso !");
            }
        atualizarTabelaUsu();
    }//GEN-LAST:event_lbBtnAddUserMouseClicked

    private void lbBtnExcluirUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUsu.getSelectedRow()!= -1){
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDadosUsu.getSelectedRow();
            String cell = tbDadosUsu.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM usuario WHERE id_usuario = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabelaUsu();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        atualizarTabelaUsu();
    }//GEN-LAST:event_lbBtnExcluirUserMouseClicked

    private void lbBtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddMouseClicked
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();

        if((txtNomeCanal.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        }else{

            canais.setNomecanal(txtNomeCanal.getText());

            int indexTipoCanal = cbTipoCanal.getSelectedIndex();
            int indexPadrao = cbPadraoAutenticacao.getSelectedIndex();
            
            canais.setUsuariocanal(txtUsuario.getText());
            canais.setSenhacanal(txtSenha.getText());
            canais.setToken(txtToken.getText());

            if (indexTipoCanal == 0){
                canais.setTipocanal("MarketPlace");
            }else if(indexTipoCanal == 1){
                canais.setTipocanal("Plataforma ERP");
            }else if(indexTipoCanal == 2){
                canais.setTipocanal("Forma de Pagamento");
            }
            if (indexPadrao == 1){
                canais.setPadraoautenticacao("Token");
            }else if(indexPadrao == 2){
                canais.setPadraoautenticacao("Senha");
            }
            dao.saveusu(canais);
            JOptionPane.showMessageDialog(null, "Canal "+txtNomeCanal.getText()+" Cadastrado com sucesso !");
            txtNomeCanal.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtToken.setText("");
            atualizarTabela();
        }
    }//GEN-LAST:event_lbBtnAddMouseClicked

    private void lbBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarMouseClicked
        //Botão de Atualizar dados dados da Tabela

        if (tbDados.getSelectedRow()!= -1){

            Canais canais = new Canais();
            CanaisDAO dao = new CanaisDAO();

            canais.setIdcanal((int) tbDados.getValueAt(tbDados.getSelectedRow(), 0));
            canais.setNomecanal(txtNomeCanal.getText());
            canais.setTipocanal(cbTipoCanal.getItemAt(cbTipoCanal.getSelectedIndex()));
            canais.setPadraoautenticacao(cbPadraoAutenticacao.getItemAt(cbPadraoAutenticacao.getSelectedIndex()));
            canais.setToken(txtToken.getText());
            canais.setUsuariocanal(txtUsuario.getText());
            canais.setSenhacanal(txtSenha.getText());
            
            dao.update(canais);

            txtNomeCanal.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtToken.setText("");

            atualizarTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarMouseClicked

    private void lbBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirMouseClicked
        // Botão excluir:
        if (tbDados.getSelectedRow()!= -1){
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDados.getSelectedRow();
            String cell = tbDados.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM canais WHERE id_canais = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabela();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        atualizarTabela();
    }//GEN-LAST:event_lbBtnExcluirMouseClicked

    private void lbBtnEditarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUsu.getSelectedRow()!= -1){

            Usuario usuario = new Usuario();
            UsuarioDAO daoUsu = new UsuarioDAO();

            usuario.setId_usuario((int) tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 0));
            usuario.setNome_usuario(txtNomeUser.getText());
            usuario.setEmail_usuario(txtEmail.getText());
            usuario.setSenha_usuario(txtSenhaUser.getText());

            daoUsu.updateUsuario(usuario);

            txtNomeUser.setText("");
            txtEmail.setText("");
            txtSenhaUser.setText("");

            atualizarTabelaUsu();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarUserMouseClicked

    private void lbBtnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnPerfilMouseClicked
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBtnPerfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesAtivas().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfigAdm;
    private javax.swing.JPanel PainelConfigUser;
    private javax.swing.JPanel PainelTabelaAdm;
    private javax.swing.JPanel PainelTabelaUsers;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnAtualizarTabela1;
    private javax.swing.JLabel btnPaginaCanais;
    private javax.swing.JLabel btnPaginaUsuario;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoBuscaUser;
    private javax.swing.JComboBox<String> cbPadraoAutenticacao;
    private javax.swing.JComboBox<String> cbTipoCanal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneTabelaUser;
    private javax.swing.JLabel lbBtnAdd;
    private javax.swing.JLabel lbBtnAddUser;
    private javax.swing.JLabel lbBtnEditar;
    private javax.swing.JLabel lbBtnEditarUser;
    private javax.swing.JLabel lbBtnExcluir;
    private javax.swing.JLabel lbBtnExcluirUser;
    private javax.swing.JLabel lbBtnFim;
    private javax.swing.JLabel lbBtnFim1;
    private javax.swing.JLabel lbBtnInicio;
    private javax.swing.JLabel lbBtnInicio1;
    private javax.swing.JLabel lbBtnNext;
    private javax.swing.JLabel lbBtnNext1;
    private javax.swing.JLabel lbBtnPerfil;
    private javax.swing.JLabel lbBtnPrev;
    private javax.swing.JLabel lbBtnPrev1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCanal;
    private javax.swing.JLabel lbNomeUser;
    private javax.swing.JLabel lbPadraoAutenticacao;
    private javax.swing.JLabel lbPesquiUser1;
    private javax.swing.JLabel lbPesquiUser2;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenhaUser;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTipoCanal;
    private javax.swing.JLabel lbToken;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelBotoesUser;
    private javax.swing.JPanel painelBtnAdd;
    private javax.swing.JPanel painelBtnAddUser;
    private javax.swing.JPanel painelBtnEditar;
    private javax.swing.JPanel painelBtnEditarUser;
    private javax.swing.JPanel painelBtnExcluir;
    private javax.swing.JPanel painelBtnExcluirUser;
    private javax.swing.JPanel painelBtnFim;
    private javax.swing.JPanel painelBtnFim1;
    private javax.swing.JPanel painelBtnIni;
    private javax.swing.JPanel painelBtnIni1;
    private javax.swing.JPanel painelBtnNext;
    private javax.swing.JPanel painelBtnNext1;
    private javax.swing.JPanel painelBtnPrev;
    private javax.swing.JPanel painelBtnPrev1;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelNaveg;
    private javax.swing.JPanel painelNavegUser;
    private javax.swing.JTable tbDados;
    private javax.swing.JTable tbDadosUsu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCanal;
    private javax.swing.JTextField txtNomeUser;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSenhaUser;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {
        
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM canais LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel)tbDados.getModel();
            modelo.setNumRows(0);
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id_canais"),
                                               rs.getString("nome_canal"),
                                               rs.getString("tipo_canal"),
                                               rs.getString("padrao_autenticacao"),
                                               rs.getString("token"),
                                               rs.getString("senha_canal")
                                                });
                }
            rs.close();
            connection.close();
            indicePaginaCanais = 0;
            lbBtnInicio.setEnabled(false);
            lbBtnPrev.setEnabled(false);
            
            if(paginaInicial <= 10){
                lbBtnNext.setEnabled(false);
                lbBtnFim.setEnabled(false);
            }else{
                lbBtnNext.setEnabled(true);
                lbBtnFim.setEnabled(true);
            }
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    private void atualizarTabelaUsu() {
        
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection(); 
            String sql = "SELECT * FROM usuario LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tbDadosUsu.getModel();
            model.setNumRows(0);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getInt("id_usuario"),
                                               rs.getString("nome_usuario"),
                                               rs.getString("email_usuario"),
                                               rs.getString("senha_usuario"),
                                                });
                }
            rs.close();
            connection.close();
            indicePaginaCanais = 0;
            lbBtnInicio1.setEnabled(false);
            lbBtnPrev1.setEnabled(false);
            if(paginaInicialUsu <= 10){
                lbBtnNext1.setEnabled(false);
                lbBtnFim1.setEnabled(false);
            }else{
                lbBtnNext1.setEnabled(true);
                lbBtnFim1.setEnabled(true);
            }
            } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}