/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexaobanco.ConexaoComBanco;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Secao;
import modelo.Usuario;
import gui.TelaConfiguracoesAtivasUser;

/**
 *
 * @author fatec
 */
public class TelaLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        btnEsconderSenha.setVisible(false);
    }
    Connection con = null;
    
    //Gradiente do JPanel de fundo
    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new jPanelGradient();
        painelLogin = new javax.swing.JPanel();
        txtEmailLogin = new javax.swing.JTextField();
        lbEmailLogin = new javax.swing.JLabel();
        lbSenhaLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lbTextoLogin = new javax.swing.JLabel();
        painelBtnAcessar = new javax.swing.JPanel();
        lbBtnAcessar = new javax.swing.JLabel();
        lbBtnCadastrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoUser = new javax.swing.JComboBox<>();
        btnEsconderSenha = new javax.swing.JButton();
        btnMostrarSenha = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        lbTxtPrincipal = new javax.swing.JLabel();
        lbTxtInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Login");
        setResizable(false);

        painelLogin.setBackground(new java.awt.Color(249, 250, 251));
        painelLogin.setPreferredSize(new java.awt.Dimension(397, 518));

        lbEmailLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbEmailLogin.setForeground(new java.awt.Color(51, 51, 51));
        lbEmailLogin.setText("E-mail:");

        lbSenhaLogin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbSenhaLogin.setForeground(new java.awt.Color(51, 51, 51));
        lbSenhaLogin.setText("Senha:");

        lbTextoLogin.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        lbTextoLogin.setForeground(new java.awt.Color(200, 88, 51));
        lbTextoLogin.setText("<html> <body style=\"text-align:center\"> <p>REALIZAR</p> <p style=\"color:#30124E\">LOGIN</p> </body> </html>");

        painelBtnAcessar.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAcessar.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lbBtnAcessar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAcessar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAcessar.setText("Acessar sistema");
        lbBtnAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAcessar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAcessarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnAcessarLayout = new javax.swing.GroupLayout(painelBtnAcessar);
        painelBtnAcessar.setLayout(painelBtnAcessarLayout);
        painelBtnAcessarLayout.setHorizontalGroup(
            painelBtnAcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnAcessarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnAcessarLayout.setVerticalGroup(
            painelBtnAcessarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnAcessarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbBtnCadastrar.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lbBtnCadastrar.setForeground(new java.awt.Color(48, 18, 78));
        lbBtnCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnCadastrar.setText("Cadastre-se");
        lbBtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnCadastrarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeEmail.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeSenha.png"))); // NOI18N

        cbTipoUser.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        cbTipoUser.setForeground(new java.awt.Color(51, 51, 51));
        cbTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Admin", "User" }));
        cbTipoUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEsconderSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoFechado.png"))); // NOI18N
        btnEsconderSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsconderSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsconderSenhaActionPerformed(evt);
            }
        });

        btnMostrarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeOlhoAberto.png"))); // NOI18N
        btnMostrarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lbEmailLogin))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lbSenhaLogin))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEsconderSenha)
                    .addComponent(btnMostrarSenha)))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(cbTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(painelBtnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lbBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lbTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lbEmailLogin)
                .addGap(6, 6, 6)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lbSenhaLogin)
                .addGap(6, 6, 6)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEsconderSenha)
                    .addComponent(btnMostrarSenha))
                .addGap(29, 29, 29)
                .addComponent(cbTipoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(painelBtnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbBtnCadastrar))
        );

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        lbTxtPrincipal.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        lbTxtPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbTxtPrincipal.setText("<html>\n<body style=\"text-align:center\"> \nUm B2B para conciliar \n<br> \nsua plataforma com as \n<br> \nsuas vendas. \n</body>\n</html>");

        lbTxtInfo.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lbTxtInfo.setForeground(new java.awt.Color(255, 255, 255));
        lbTxtInfo.setText("<html>\n<body style=\"text-align:center\">\nConcilie as vendas e pagamentos do seu e-commerce,\n<br>\nmarketplace, lojas físicas. Tenha tudo isso \n<br>\nem um único painel que te permite criar \n<br>\nestratégias financeiras mais assertivas e identificar\n<br>\ngargalos no final do mês.\n</body>\n</html>");

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lbTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lbTxtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo)
                .addGap(771, 771, 771))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(lbTxtPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbBtnAcessarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAcessarMouseClicked
        // Fazer o login
        Usuario objUsu = new Usuario();
        Secao secaoUsu = new Secao();

        String indexComboBox = (String) cbTipoUser.getSelectedItem();
        while (txtEmailLogin.getText().equals("") || txtSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            break;
        }
        while (indexComboBox.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um tipo de Usuario");
            break;
        }

        objUsu.setEmail_usuario(txtEmailLogin.getText());
        objUsu.setSenha_usuario(txtSenha.getText());
        objUsu.setTipo_usuario((String) cbTipoUser.getSelectedItem());
        
        secaoUsu.setEmail_user(txtEmailLogin.getText());
        secaoUsu.setTipo_user((String) cbTipoUser.getSelectedItem());

        UsuarioDAO objUsuDAO = new UsuarioDAO();

        ResultSet rsUsuDAO = objUsuDAO.autenticacaoUsuario(objUsu);
        try {
            if (rsUsuDAO.next()) {
                int idUsuario = rsUsuDAO.getInt("id_usuario");
                String dadoCbTipo = secaoUsu.getTipo_user();
                if (dadoCbTipo == "Admin") {
                    String sql = "INSERT INTO secao(email_user, tipo_user, id_user, id_geral) VALUES(?, ?, 1, ?)";
                    con = new ConexaoComBanco().getConnection();
                    try {
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setString(1, secaoUsu.getEmail_user());
                        stmt.setString(2, secaoUsu.getTipo_user());
                        stmt.setInt(3, rsUsuDAO.getInt("id_usuario"));
                        stmt.execute();
                    } catch (SQLException u) {
                        System.out.print("Erro no ADM " + u);
                    }
                    TelaConfiguracoesAtivas telaAdm = new TelaConfiguracoesAtivas();
                    telaAdm.setVisible(true);
                    this.dispose();
                } else if (dadoCbTipo == "User") {
                    String sql = "INSERT INTO secao(email_user, tipo_user, id_user, id_geral) VALUES(?, ?, 1, ?)";
                    con = new ConexaoComBanco().getConnection();
                    try {
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setString(1, secaoUsu.getEmail_user());
                        stmt.setString(2, secaoUsu.getTipo_user());
                        stmt.setInt(3, rsUsuDAO.getInt("id_usuario"));
                        stmt.execute();
                    } catch (SQLException u) {
                        System.out.print("Erro no USER " + u);
                    }
                    TelaConfiguracoesAtivasUser telaUser = new TelaConfiguracoesAtivasUser(idUsuario);
                    objUsu.setEmail_usuario(txtEmailLogin.getText());
                    telaUser.ObterUsuario(idUsuario);
                    telaUser.setVisible(true);
                    
                    
                    this.dispose();
                    

                }
            } else {
                JOptionPane.showMessageDialog(null, "Email ou Senha Incorretos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no Login" + ex);
        }
    }//GEN-LAST:event_lbBtnAcessarMouseClicked

    private void lbBtnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnCadastrarMouseClicked
        // Abrir página cadastro
        TelaCadastro telacadastro = new TelaCadastro();
        telacadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBtnCadastrarMouseClicked

    private void btnEsconderSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsconderSenhaActionPerformed
        txtSenha.setEchoChar('*'); // Com echo char, é possível definir um caractere que aparecerá sempre que um usuário digitar a senha no JPasswordField.
        btnMostrarSenha.setVisible(true);
        btnEsconderSenha.setVisible(false);
    }//GEN-LAST:event_btnEsconderSenhaActionPerformed

    private void btnMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSenhaActionPerformed
        txtSenha.setEchoChar('\u0000'); //Aqui é onde definimos o JPassoword para colocar a senha vísivel. Um char tem um valor padrão de 'u0000'.
        btnMostrarSenha.setVisible(false);
        btnEsconderSenha.setVisible(true);
    }//GEN-LAST:event_btnMostrarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsconderSenha;
    private javax.swing.JButton btnMostrarSenha;
    private javax.swing.JComboBox<String> cbTipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbBtnAcessar;
    private javax.swing.JLabel lbBtnCadastrar;
    private javax.swing.JLabel lbEmailLogin;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbSenhaLogin;
    private javax.swing.JLabel lbTextoLogin;
    private javax.swing.JLabel lbTxtInfo;
    private javax.swing.JLabel lbTxtPrincipal;
    private javax.swing.JPanel painelBtnAcessar;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

     
}

