/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexaobanco.ConexaoComBanco;
import dao.UsuarioDAO;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Secao;
import modelo.Usuario;


/**
 *
 * @author joaog
 */
public class TelaConfiguracoesConta extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfiguracoesConta
     */
    Connection con = null;
    Secao secaoUsu = new Secao();
    PreparedStatement ps = null;
    ResultSet rs = null;
    int idUsuario = idUsu();

    public TelaConfiguracoesConta() {
        initComponents();
        String sql = "SELECT email_user FROM secao where id_user = 1";
        con = new ConexaoComBanco().getConnection();

        try {
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                secaoUsu.setEmail_user(rs.getString("email_user"));
            }
        } catch (SQLException u) {
            throw new RuntimeException(u);
        }
        
        String sqlId = "SELECT * FROM usuario where id_usuario =" + idUsuario + "";
        
        try {
            ps = con.prepareStatement(sqlId);
            rs = ps.executeQuery();
            
            while (rs.next()) {
                txtNome.setText(rs.getString("nome_usuario"));
                txtEmail.setText(rs.getString("email_usuario"));
                txtSenha.setText(rs.getString("senha_usuario"));
            }
        } catch (SQLException u) {
            throw new RuntimeException(u);
        }

//        lbNomePerfil.setText(objUsu.getNome_usuario());
        lbEmailUser.setText((String) secaoUsu.getEmail_user());
        
        txtNome.setEnabled(false);
        txtEmail.setEnabled(false);
        txtSenha.setEnabled(false);
    }
    
    public int idUsu() {
        String sqlIdG = "SELECT id_geral FROM secao where id_user = 1";
        con = new ConexaoComBanco().getConnection();
        int idEditUser = 0;

        try {
            ps = con.prepareStatement(sqlIdG);
            rs = ps.executeQuery();
            while (rs.next()) {
                idEditUser = rs.getInt("id_geral");
            }
        } catch (SQLException u) {
            throw new RuntimeException(u);
        }
        return idEditUser;
    }
    
    public boolean updatePerfil(Usuario usuario) {
        String sqlUpdate = "UPDATE usuario SET nome_usuario = ?, email_usuario = ?,senha_usuario = ? WHERE id_usuario =" + idUsuario + "";

        PreparedStatement stmt = null;

        try {
            stmt = con.prepareStatement(sqlUpdate);
            stmt.setString(1, usuario.getNome_usuario());
            stmt.setString(2, usuario.getEmail_usuario());
            stmt.setString(3, usuario.getSenha_usuario());
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            System.err.println("Erro!" + ex);
            return false;
        }
    }
    

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(850, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new jPanelGradient();
        lbLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbEmailUser = new javax.swing.JLabel();
        painelConfigurar = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lbBotaoEditar = new javax.swing.JLabel();
        lbTextoLogin = new javax.swing.JLabel();
        painelLinha = new javax.swing.JPanel();
        painelBtnSalvar = new javax.swing.JPanel();
        lbBtnSalvar = new javax.swing.JLabel();
        iconeUser = new javax.swing.JLabel();
        iconeEmail = new javax.swing.JLabel();
        iconeSenha = new javax.swing.JLabel();
        lbBtnEditar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbBtnSair = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(977, 630));
        setResizable(false);

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconePerfil.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbEmailUser.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbEmailUser.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailUser.setText("Teste");

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEmailUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbEmailUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelConfigurar.setBackground(new java.awt.Color(249, 250, 251));

        txtNome.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbNome.setForeground(new java.awt.Color(51, 51, 51));
        lbNome.setText("Nome:");

        lbEmail.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("E-mail:");

        lbSenha.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(51, 51, 51));
        lbSenha.setText("Senha:");

        txtSenha.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        lbBotaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbTextoLogin.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        lbTextoLogin.setForeground(new java.awt.Color(200, 88, 51));
        lbTextoLogin.setText("<html>\n<body style=\"text-align:center\">\n<p>CONFIGURAR CONTA</p>\n<p style=\"color:#30124E\">DO USUÁRIO</p>\n</body>\n</html>");

        painelLinha.setPreferredSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout painelLinhaLayout = new javax.swing.GroupLayout(painelLinha);
        painelLinha.setLayout(painelLinhaLayout);
        painelLinhaLayout.setHorizontalGroup(
            painelLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        painelLinhaLayout.setVerticalGroup(
            painelLinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelBtnSalvar.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnSalvar.setFont(new java.awt.Font("Inter", 1, 15)); // NOI18N
        lbBtnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnSalvar.setText("Salvar");
        lbBtnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnSalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnSalvarLayout = new javax.swing.GroupLayout(painelBtnSalvar);
        painelBtnSalvar.setLayout(painelBtnSalvarLayout);
        painelBtnSalvarLayout.setHorizontalGroup(
            painelBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );
        painelBtnSalvarLayout.setVerticalGroup(
            painelBtnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        iconeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeUsuario.png"))); // NOI18N

        iconeEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeEmail.png"))); // NOI18N

        iconeSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeSenha.png"))); // NOI18N

        lbBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeLapis.png"))); // NOI18N
        lbBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeVoltar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConfigurarLayout = new javax.swing.GroupLayout(painelConfigurar);
        painelConfigurar.setLayout(painelConfigurarLayout);
        painelConfigurarLayout.setHorizontalGroup(
            painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfigurarLayout.createSequentialGroup()
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConfigurarLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelConfigurarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(painelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConfigurarLayout.createSequentialGroup()
                        .addComponent(lbBotaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBtnEditar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConfigurarLayout.createSequentialGroup()
                        .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconeUser)
                            .addComponent(iconeEmail)
                            .addComponent(iconeSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSenha)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );

        painelConfigurarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {painelBtnSalvar, txtEmail, txtNome, txtSenha});

        painelConfigurarLayout.setVerticalGroup(
            painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConfigurarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(lbTextoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painelLinha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(painelConfigurarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBotaoEditar)
                    .addComponent(lbBtnEditar))
                .addGap(70, 70, 70)
                .addComponent(lbNome)
                .addGap(6, 6, 6)
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelConfigurarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(painelBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        painelConfigurarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {painelBtnSalvar, txtEmail, txtNome, txtSenha});

        lbBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeSair.png"))); // NOI18N
        lbBtnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(painelConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbBtnSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(painelConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lbBtnSair)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void lbBtnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnSalvarMouseClicked
        Usuario usuario = new Usuario();
        UsuarioDAO daoUsu = new UsuarioDAO();

        usuario.setNome_usuario(txtNome.getText());
        usuario.setEmail_usuario(txtEmail.getText());
        usuario.setSenha_usuario(txtSenha.getText());

        updatePerfil(usuario);
        
        JOptionPane.showMessageDialog(null, "Informações editadas com sucesso!");
        
        txtNome.setEnabled(false);
        txtEmail.setEnabled(false);
        txtSenha.setEnabled(false);
    }//GEN-LAST:event_lbBtnSalvarMouseClicked

    private void lbBtnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnSairMouseClicked
        // TODO add your handling code here:
        ConexaoComBanco ccb = new ConexaoComBanco();
        Connection connection = ccb.getConnection();
        String sql = "DELETE FROM secao WHERE id_user = 1 ";
        try {
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Voce Deslogou do Sistema");
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBtnSairMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        int idUsu = 0;
        try {
            
                String sql = "SELECT tipo_user,id_geral FROM secao where id_user = 1";
                con = new ConexaoComBanco().getConnection();
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();

                while (rs.next()) {
                    String tipoUser = rs.getString("tipo_user");
                    secaoUsu.setTipo_user(tipoUser);
                    idUsu = rs.getInt("id_geral");
                }

                String tipoUser = secaoUsu.getTipo_user();

                if (tipoUser.equals("Admin")) {
                    TelaConfiguracoesAtivas telaAdm = new TelaConfiguracoesAtivas();
                    telaAdm.setVisible(true);
                    this.dispose();
                } else if (tipoUser.equals("User")) {
                    TelaConfiguracoesAtivasUser telaUser = new TelaConfiguracoesAtivasUser(idUsu);
                    telaUser.ObterUsuario(idUsu);
                    telaUser.setVisible(true);
                    this.dispose();
                }
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(TelaConfiguracoesConta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarMouseClicked
        txtNome.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSenha.setEnabled(true);
    }//GEN-LAST:event_lbBtnEditarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconeEmail;
    private javax.swing.JLabel iconeSenha;
    private javax.swing.JLabel iconeUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbBotaoEditar;
    private javax.swing.JLabel lbBtnEditar;
    private javax.swing.JLabel lbBtnSair;
    private javax.swing.JLabel lbBtnSalvar;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailUser;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTextoLogin;
    private javax.swing.JPanel painelBtnSalvar;
    private javax.swing.JPanel painelConfigurar;
    private javax.swing.JPanel painelLinha;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
