/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conexaobanco.ConexaoComBanco;
import dao.CanaisDAO;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Canais;
import modelo.Secao;
import modelo.Usuario;

/**
 *
 * @author Rebeca
 */
public class TelaConfiguracoesAtivas extends JFrame {

    /**
     * Creates new form TelaConfiguraçõesAtivas
     */
    Connection con = null;
    CanaisDAO dao = new CanaisDAO();
    UsuarioDAO daoUsu = new UsuarioDAO();
    Secao secaoUsu = new Secao();
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel dm = (DefaultTableModel) dao.fetchBySize(0, 10);
    DefaultTableModel dmusu = (DefaultTableModel) daoUsu.fetchBySizeUsu(0, 10);
    int indexAbas = 1;
    int indicePaginaCanais = 0;
    int indicePaginaUsuario = 0;

    int paginaInicial = (int) dao.getRowCount();
    int paginaInicialUsu = (int) daoUsu.getRowCountUsu();

    public TelaConfiguracoesAtivas() {

        initComponents();
        
        String sql = "SELECT email_user FROM secao where id_user = 1";
        con = new ConexaoComBanco().getConnection();

        try {
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                secaoUsu.setEmail_user(rs.getString("email_user"));
            }
        } catch (SQLException u) {
            throw new RuntimeException(u);
        }

        lbEmailPefil.setText((String)secaoUsu.getEmail_user());

        atualizarTabela();

        //PAGINAÇÃO TABELA CANAIS
        tbDados.setModel(dm);
        btnPrev.setEnabled(false);
        btnStart.setEnabled(false);

        if (paginaInicial <= 10) {
            btnNext.setEnabled(false);
            btnEnd.setEnabled(false);
        }
        //PAGINAÇÃO TABELA USUARIO
        tbDadosUsu.setModel(dmusu);
        btnPrev2.setEnabled(false);
        btnStart2.setEnabled(false);

        if (paginaInicialUsu <= 10) {
            btnNext2.setEnabled(false);
            btnEnd2.setEnabled(false);
        }

        //GUIA DE ABAS
        PainelTabelaUsers.setVisible(false);
        PainelConfigUser.setVisible(false);

        if (indexAbas % 2 != 0) {
            PainelTabelaAdm.setVisible(true);
            PainelConfigAdm.setVisible(true);
            btnPaginaCanais.setEnabled(false);
        }

    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(48, 18, 78);
            Color color2 = new Color(200, 88, 51);
            GradientPaint gp = new GradientPaint(850, 0, color1, 0, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenu = new jPanelGradient();
        lbLogo = new javax.swing.JLabel();
        lbBtnPerfil = new javax.swing.JLabel();
        lbEmailPefil = new javax.swing.JLabel();
        lbTexto = new javax.swing.JLabel();
        painelFundo = new javax.swing.JPanel();
        btnPaginaCanais = new javax.swing.JLabel();
        btnPaginaUsuario = new javax.swing.JLabel();
        PainelTabelaUsers = new javax.swing.JPanel();
        campoBuscaUser = new javax.swing.JTextField();
        jScrollPaneTabelaUser = new javax.swing.JScrollPane();
        tbDadosUsu = new javax.swing.JTable();
        lbPesquiUser1 = new javax.swing.JLabel();
        painelNaveg2 = new javax.swing.JPanel();
        btnAtualizarTabela3 = new javax.swing.JButton();
        btnStart2 = new javax.swing.JButton();
        btnNext2 = new javax.swing.JButton();
        btnPrev2 = new javax.swing.JButton();
        btnEnd2 = new javax.swing.JButton();
        PainelTabelaAdm = new javax.swing.JPanel();
        campoBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        painelNaveg = new javax.swing.JPanel();
        btnAtualizarTabela = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        lbPesquiUser2 = new javax.swing.JLabel();
        PainelConfigUser = new javax.swing.JPanel();
        lbNomeUser = new javax.swing.JLabel();
        txtNomeUser = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbSenhaUser = new javax.swing.JLabel();
        txtSenhaUser = new javax.swing.JTextField();
        painelBotoesUser = new javax.swing.JPanel();
        painelBtnAddUser = new javax.swing.JPanel();
        lbBtnAddUser = new javax.swing.JLabel();
        painelBtnEditarUser = new javax.swing.JPanel();
        lbBtnEditarUser = new javax.swing.JLabel();
        painelBtnExcluirUser = new javax.swing.JPanel();
        lbBtnExcluirUser = new javax.swing.JLabel();
        PainelConfigAdm = new javax.swing.JPanel();
        lbNomeCanal = new javax.swing.JLabel();
        txtNomeCanal = new javax.swing.JTextField();
        lbTipoCanal = new javax.swing.JLabel();
        cbTipoCanal = new javax.swing.JComboBox<>();
        lbPadraoAutenticacao = new javax.swing.JLabel();
        cbPadraoAutenticacao = new javax.swing.JComboBox<>();
        painelBotoes = new javax.swing.JPanel();
        painelBtnAdd = new javax.swing.JPanel();
        lbBtnAdd = new javax.swing.JLabel();
        painelBtnEditar = new javax.swing.JPanel();
        lbBtnEditar = new javax.swing.JLabel();
        painelBtnExcluir = new javax.swing.JPanel();
        lbBtnExcluir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Track Cash - Sistema de autorização");
        setResizable(false);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTrackCashB.png"))); // NOI18N

        lbBtnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconePerfil.png"))); // NOI18N
        lbBtnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnPerfilMouseClicked(evt);
            }
        });

        lbEmailPefil.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbEmailPefil.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailPefil.setText("Teste");

        javax.swing.GroupLayout painelMenuLayout = new javax.swing.GroupLayout(painelMenu);
        painelMenu.setLayout(painelMenuLayout);
        painelMenuLayout.setHorizontalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuLayout.createSequentialGroup()
                .addComponent(lbLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbEmailPefil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelMenuLayout.setVerticalGroup(
            painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBtnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbEmailPefil)
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );

        lbTexto.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lbTexto.setText("<html>\n<body style=\"text-align:center\">\nOlá, seja bem vindo! Aqui você pode visualizar, editar ou adicionar os canais cadastrados na\n<br>\n tabela abaixo!\n</body>\n</html>");

        painelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPaginaCanais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeTabelaCanais.png"))); // NOI18N
        btnPaginaCanais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaginaCanais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaginaCanaisMouseClicked(evt);
            }
        });
        painelFundo.add(btnPaginaCanais, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnPaginaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeTabelaUsers.png"))); // NOI18N
        btnPaginaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaginaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaginaUsuarioMouseClicked(evt);
            }
        });
        painelFundo.add(btnPaginaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        PainelTabelaUsers.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBuscaUser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        campoBuscaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaUserjTextField_pesqActionPerformed(evt);
            }
        });
        campoBuscaUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaUserKeyTyped(evt);
            }
        });
        PainelTabelaUsers.add(campoBuscaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 740, 30));

        tbDadosUsu.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tbDadosUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Email", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDadosUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosUsuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosUsuMousePressed(evt);
            }
        });
        jScrollPaneTabelaUser.setViewportView(tbDadosUsu);

        PainelTabelaUsers.add(jScrollPaneTabelaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 233));

        lbPesquiUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaUsers.add(lbPesquiUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        painelNaveg2.setBackground(new java.awt.Color(232, 232, 232));

        btnAtualizarTabela3.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabela3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizarTabela3.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabela3.setBorder(null);
        btnAtualizarTabela3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabela3ActionPerformed(evt);
            }
        });

        btnStart2.setBackground(new java.awt.Color(217, 90, 48));
        btnStart2.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnStart2.setForeground(new java.awt.Color(255, 255, 255));
        btnStart2.setText("Início");
        btnStart2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        btnNext2.setBackground(new java.awt.Color(217, 90, 48));
        btnNext2.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnNext2.setForeground(new java.awt.Color(255, 255, 255));
        btnNext2.setText(">>");
        btnNext2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext2MouseClicked(evt);
            }
        });
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        btnPrev2.setBackground(new java.awt.Color(217, 90, 48));
        btnPrev2.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnPrev2.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev2.setText("<<");
        btnPrev2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrev2MouseClicked(evt);
            }
        });
        btnPrev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev2ActionPerformed(evt);
            }
        });

        btnEnd2.setBackground(new java.awt.Color(217, 90, 48));
        btnEnd2.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnEnd2.setForeground(new java.awt.Color(255, 255, 255));
        btnEnd2.setText("Fim");
        btnEnd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelNaveg2Layout = new javax.swing.GroupLayout(painelNaveg2);
        painelNaveg2.setLayout(painelNaveg2Layout);
        painelNaveg2Layout.setHorizontalGroup(
            painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNaveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrev2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAtualizarTabela3)
                .addGap(12, 12, 12)
                .addComponent(btnNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelNaveg2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEnd2, btnNext2, btnPrev2, btnStart2});

        painelNaveg2Layout.setVerticalGroup(
            painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNaveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext2)
                        .addComponent(btnEnd2))
                    .addGroup(painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAtualizarTabela3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNaveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart2)
                            .addComponent(btnPrev2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelNaveg2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEnd2, btnNext2, btnPrev2, btnStart2});

        PainelTabelaUsers.add(painelNaveg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 340, 40));

        painelFundo.add(PainelTabelaUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 880, 340));

        PainelTabelaAdm.setBackground(new java.awt.Color(232, 232, 232));
        PainelTabelaAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoBusca.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pesqActionPerformed(evt);
            }
        });
        campoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoBuscaKeyTyped(evt);
            }
        });
        PainelTabelaAdm.add(campoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 742, 30));

        tbDados.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id", "Canais", "Tipo", "Padão de Autentificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbDadosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbDados);

        PainelTabelaAdm.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 233));

        painelNaveg.setBackground(new java.awt.Color(232, 232, 232));

        btnAtualizarTabela.setBackground(new java.awt.Color(232, 232, 232));
        btnAtualizarTabela.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnAtualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atualizar.png"))); // NOI18N
        btnAtualizarTabela.setBorder(null);
        btnAtualizarTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(217, 90, 48));
        btnStart.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Inicio");
        btnStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(217, 90, 48));
        btnNext.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new java.awt.Color(217, 90, 48));
        btnPrev.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnEnd.setBackground(new java.awt.Color(217, 90, 48));
        btnEnd.setFont(new java.awt.Font("Inter", 1, 11)); // NOI18N
        btnEnd.setForeground(new java.awt.Color(255, 255, 255));
        btnEnd.setText("Fim");
        btnEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelNavegLayout = new javax.swing.GroupLayout(painelNaveg);
        painelNaveg.setLayout(painelNavegLayout);
        painelNavegLayout.setHorizontalGroup(
            painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAtualizarTabela)
                .addGap(12, 12, 12)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelNavegLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEnd, btnNext, btnPrev, btnStart});

        painelNavegLayout.setVerticalGroup(
            painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNavegLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnEnd))
                    .addGroup(painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAtualizarTabela)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNavegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(btnPrev))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelNavegLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEnd, btnNext, btnPrev, btnStart});

        PainelTabelaAdm.add(painelNaveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 340, 40));

        lbPesquiUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        PainelTabelaAdm.add(lbPesquiUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        painelFundo.add(PainelTabelaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 40, 880, 340));

        PainelConfigUser.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeUser.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbNomeUser.setForeground(new java.awt.Color(51, 51, 51));
        lbNomeUser.setText("Nome :");
        PainelConfigUser.add(lbNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        txtNomeUser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtNomeUser.setForeground(new java.awt.Color(51, 51, 51));
        PainelConfigUser.add(txtNomeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 52, 239, -1));

        txtEmail.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        PainelConfigUser.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 152, -1));

        lbEmail.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(51, 51, 51));
        lbEmail.setText("E-mail : ");
        PainelConfigUser.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lbSenhaUser.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbSenhaUser.setForeground(new java.awt.Color(51, 51, 51));
        lbSenhaUser.setText("Senha : ");
        PainelConfigUser.add(lbSenhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        txtSenhaUser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtSenhaUser.setForeground(new java.awt.Color(51, 51, 51));
        txtSenhaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaUserActionPerformed(evt);
            }
        });
        PainelConfigUser.add(txtSenhaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 147, -1));

        painelBotoesUser.setBackground(new java.awt.Color(249, 250, 251));

        painelBtnAddUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAddUser.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAddUser.setText("ADICIONAR");
        lbBtnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnAddUserLayout = new javax.swing.GroupLayout(painelBtnAddUser);
        painelBtnAddUser.setLayout(painelBtnAddUserLayout);
        painelBtnAddUserLayout.setHorizontalGroup(
            painelBtnAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBtnAddUserLayout.setVerticalGroup(
            painelBtnAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        painelBtnEditarUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditarUser.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnEditarUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditarUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditarUser.setText("EDITAR");
        lbBtnEditarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnEditarUserLayout = new javax.swing.GroupLayout(painelBtnEditarUser);
        painelBtnEditarUser.setLayout(painelBtnEditarUserLayout);
        painelBtnEditarUserLayout.setHorizontalGroup(
            painelBtnEditarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnEditarUserLayout.setVerticalGroup(
            painelBtnEditarUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnExcluirUser.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluirUser.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnExcluirUser.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluirUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluirUser.setText("EXCLUIR");
        lbBtnExcluirUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluirUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnExcluirUserLayout = new javax.swing.GroupLayout(painelBtnExcluirUser);
        painelBtnExcluirUser.setLayout(painelBtnExcluirUserLayout);
        painelBtnExcluirUserLayout.setHorizontalGroup(
            painelBtnExcluirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBtnExcluirUserLayout.createSequentialGroup()
                .addComponent(lbBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBtnExcluirUserLayout.setVerticalGroup(
            painelBtnExcluirUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnExcluirUserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelBotoesUserLayout = new javax.swing.GroupLayout(painelBotoesUser);
        painelBotoesUser.setLayout(painelBotoesUserLayout);
        painelBotoesUserLayout.setHorizontalGroup(
            painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelBtnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnEditarUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnExcluirUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesUserLayout.setVerticalGroup(
            painelBotoesUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBtnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnEditarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnExcluirUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelConfigUser.add(painelBotoesUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 140, -1));

        painelFundo.add(PainelConfigUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 880, -1));

        PainelConfigAdm.setBackground(new java.awt.Color(249, 250, 251));
        PainelConfigAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNomeCanal.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbNomeCanal.setForeground(new java.awt.Color(51, 51, 51));
        lbNomeCanal.setText("Nome :");
        PainelConfigAdm.add(lbNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtNomeCanal.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtNomeCanal.setForeground(new java.awt.Color(51, 51, 51));
        PainelConfigAdm.add(txtNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 239, -1));

        lbTipoCanal.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbTipoCanal.setForeground(new java.awt.Color(51, 51, 51));
        lbTipoCanal.setText("Tipo :");
        PainelConfigAdm.add(lbTipoCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        cbTipoCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "MarketPlace", "PlataformaERP", "Forma de Pagamento" }));
        cbTipoCanal.setBorder(null);
        cbTipoCanal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbTipoCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoCanalActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbTipoCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 147, -1));

        lbPadraoAutenticacao.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        lbPadraoAutenticacao.setForeground(new java.awt.Color(51, 51, 51));
        lbPadraoAutenticacao.setText("Padrão Autenticação :");
        PainelConfigAdm.add(lbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        cbPadraoAutenticacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Token", "Senha" }));
        cbPadraoAutenticacao.setBorder(null);
        cbPadraoAutenticacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbPadraoAutenticacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPadraoAutenticacaoActionPerformed(evt);
            }
        });
        PainelConfigAdm.add(cbPadraoAutenticacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 147, -1));

        painelBotoes.setBackground(new java.awt.Color(249, 250, 251));

        painelBtnAdd.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnAdd.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnAdd.setText("ADICIONAR");
        lbBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnAddLayout = new javax.swing.GroupLayout(painelBtnAdd);
        painelBtnAdd.setLayout(painelBtnAddLayout);
        painelBtnAddLayout.setHorizontalGroup(
            painelBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelBtnAddLayout.setVerticalGroup(
            painelBtnAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        painelBtnEditar.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnEditar.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnEditar.setText("EDITAR");
        lbBtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnEditarLayout = new javax.swing.GroupLayout(painelBtnEditar);
        painelBtnEditar.setLayout(painelBtnEditarLayout);
        painelBtnEditarLayout.setHorizontalGroup(
            painelBtnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelBtnEditarLayout.setVerticalGroup(
            painelBtnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelBtnExcluir.setBackground(new java.awt.Color(200, 88, 51));

        lbBtnExcluir.setFont(new java.awt.Font("Inter", 1, 13)); // NOI18N
        lbBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        lbBtnExcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBtnExcluir.setText("EXCLUIR");
        lbBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBtnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBtnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBtnExcluirLayout = new javax.swing.GroupLayout(painelBtnExcluir);
        painelBtnExcluir.setLayout(painelBtnExcluirLayout);
        painelBtnExcluirLayout.setHorizontalGroup(
            painelBtnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBtnExcluirLayout.createSequentialGroup()
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelBtnExcluirLayout.setVerticalGroup(
            painelBtnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBtnExcluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelBtnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBtnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelConfigAdm.add(painelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        painelFundo.add(PainelConfigAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 880, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
                    .addComponent(painelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoCanalActionPerformed

    private void cbPadraoAutenticacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPadraoAutenticacaoActionPerformed

    }//GEN-LAST:event_cbPadraoAutenticacaoActionPerformed

    private void campoBuscaUserjTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaUserjTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserjTextField_pesqActionPerformed

    private void campoBuscaUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaUserKeyPressed

    private void campoBuscaUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaUserKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM usuario WHERE nome_usuario LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%" + campoBuscaUser.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modeloUsu = (DefaultTableModel) tbDadosUsu.getModel();
            modeloUsu.setNumRows(0);
            while (rs.next()) {
                modeloUsu.addRow(new Object[]{rs.getInt("id_usuario"),
                    rs.getString("nome_usuario"),
                    rs.getString("email_usuario"),
                    rs.getString("senha_usuario"),});
            }
            rs.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaUserKeyTyped

    private void tbDadosUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUsuMouseClicked
        // TODO add your handling code here:
        if (tbDados.getSelectedRow() != -1) {
            txtNomeUser.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 1).toString());
            txtEmail.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 2).toString());
            txtSenhaUser.setText(tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbDadosUsuMouseClicked

    private void tbDadosUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosUsuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosUsuMousePressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSenhaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaUserActionPerformed

    private void btnPaginaCanaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaginaCanaisMouseClicked
        // TODO add your handling code here:
        indexAbas = indexAbas + 1;
        if (indexAbas % 2 != 0) {
            PainelTabelaAdm.setVisible(true);
            PainelConfigAdm.setVisible(true);
            PainelTabelaUsers.setVisible(false);
            PainelConfigUser.setVisible(false);

            btnPaginaCanais.setEnabled(false);
            btnPaginaUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_btnPaginaCanaisMouseClicked

    private void btnPaginaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaginaUsuarioMouseClicked
        // TODO add your handling code here:
        indexAbas = indexAbas + 1;
        if (indexAbas % 2 == 0) {
            PainelTabelaUsers.setVisible(true);
            PainelConfigUser.setVisible(true);
            PainelTabelaAdm.setVisible(false);
            PainelConfigAdm.setVisible(false);

            btnPaginaUsuario.setEnabled(false);
            btnPaginaCanais.setEnabled(true);
        }
    }//GEN-LAST:event_btnPaginaUsuarioMouseClicked

    private void lbBtnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddUserMouseClicked
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        UsuarioDAO daoUsu = new UsuarioDAO();

        if (txtNomeUser.getText().isEmpty() || txtEmail.getText().isEmpty() || txtSenhaUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        } else {
            usuario.setNome_usuario(txtNomeUser.getText());
            usuario.setEmail_usuario(txtEmail.getText());
            usuario.setSenha_usuario(txtSenhaUser.getText());
            daoUsu.adicionaUsuario(usuario);
            JOptionPane.showMessageDialog(null, "Usuario " + txtNomeUser.getText() + " Cadastrado com sucesso !");
        }
        txtNomeUser.setText("");
        txtEmail.setText("");
        txtSenhaUser.setText("");
        
        atualizarTabelaUsu();
        
    }//GEN-LAST:event_lbBtnAddUserMouseClicked

    private void lbBtnExcluirUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUsu.getSelectedRow() != -1) {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDadosUsu.getSelectedRow();
            String cell = tbDadosUsu.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM usuario WHERE id_usuario = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabelaUsu();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        
        txtNomeUser.setText("");
        txtEmail.setText("");
        txtSenhaUser.setText("");
        
        atualizarTabelaUsu();
    }//GEN-LAST:event_lbBtnExcluirUserMouseClicked

    private void lbBtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnAddMouseClicked
        // TODO add your handling code here:
        Canais canais = new Canais();
        CanaisDAO dao = new CanaisDAO();

        if ((txtNomeCanal.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "ATENÇÃO - Preencha todos os campos !");
        } else {

            canais.setNomecanal(txtNomeCanal.getText());

            int indexTipoCanal = cbTipoCanal.getSelectedIndex();
            int indexPadrao = cbPadraoAutenticacao.getSelectedIndex();

            if (indexTipoCanal == 0) {
                canais.setTipocanal("MarketPlace");
            } else if (indexTipoCanal == 1) {
                canais.setTipocanal("Plataforma ERP");
            } else if (indexTipoCanal == 2) {
                canais.setTipocanal("Forma de Pagamento");
            }
            if (indexPadrao == 1) {
                canais.setPadraoautenticacao("Token");
            } else if (indexPadrao == 2) {
                canais.setPadraoautenticacao("Senha");
            }
            dao.saveusu(canais);
            JOptionPane.showMessageDialog(null, "Canal " + txtNomeCanal.getText() + " Cadastrado com sucesso !");
            txtNomeCanal.setText("");
            cbTipoCanal.setSelectedIndex(0);
            cbPadraoAutenticacao.setSelectedIndex(0);
            atualizarTabela();
        }
    }//GEN-LAST:event_lbBtnAddMouseClicked

    private void lbBtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarMouseClicked
        //Botão de Atualizar dados dados da Tabela

        if (tbDados.getSelectedRow() != -1) {

            Canais canais = new Canais();
            CanaisDAO dao = new CanaisDAO();

            canais.setIdcanal((int) tbDados.getValueAt(tbDados.getSelectedRow(), 0));
            canais.setNomecanal(txtNomeCanal.getText());
            canais.setTipocanal(cbTipoCanal.getItemAt(cbTipoCanal.getSelectedIndex()));
            canais.setPadraoautenticacao(cbPadraoAutenticacao.getItemAt(cbPadraoAutenticacao.getSelectedIndex()));

            dao.update(canais);

            txtNomeCanal.setText("");
            cbTipoCanal.setSelectedIndex(0);
            cbPadraoAutenticacao.setSelectedIndex(0);

            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarMouseClicked

    private void lbBtnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnExcluirMouseClicked
        // Botão excluir:
        if (tbDados.getSelectedRow() != -1) {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            int row = tbDados.getSelectedRow();
            String cell = tbDados.getModel().getValueAt(row, 0).toString();
            String sql = "DELETE FROM canais WHERE id_canais = " + cell;
            try {
                PreparedStatement stmt = connection.prepareStatement(sql);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                atualizarTabela();
                connection.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        
        txtNomeCanal.setText("");
        cbTipoCanal.setSelectedIndex(0);
        cbPadraoAutenticacao.setSelectedIndex(0);
            
        atualizarTabela();
    }//GEN-LAST:event_lbBtnExcluirMouseClicked

    private void lbBtnEditarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnEditarUserMouseClicked
        // TODO add your handling code here:
        if (tbDadosUsu.getSelectedRow() != -1) {

            Usuario usuario = new Usuario();
            UsuarioDAO daoUsu = new UsuarioDAO();

            usuario.setId_usuario((int) tbDadosUsu.getValueAt(tbDadosUsu.getSelectedRow(), 0));
            usuario.setNome_usuario(txtNomeUser.getText());
            usuario.setEmail_usuario(txtEmail.getText());
            usuario.setSenha_usuario(txtSenhaUser.getText());

            daoUsu.updateUsuario(usuario);

            txtNomeUser.setText("");
            txtEmail.setText("");
            txtSenhaUser.setText("");

            atualizarTabelaUsu();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_lbBtnEditarUserMouseClicked

    private void lbBtnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBtnPerfilMouseClicked
        // TODO add your handling code here:
        TelaConfiguracoesConta telaConfigConta = new TelaConfiguracoesConta();
        telaConfigConta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbBtnPerfilMouseClicked

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        int index = (int) dao.getRowCount();

        int valorfinal = index / 10;
        int valortotal = valorfinal * 10;
        System.out.println(valorfinal);
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(valortotal, 10);
        tbDados.setModel(pagina);
        btnNext.setEnabled(false);
        btnEnd.setEnabled(false);
        btnStart.setEnabled(true);
        btnPrev.setEnabled(true);
        indicePaginaCanais = valortotal;
    }//GEN-LAST:event_btnEndActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        int tamanho = indicePaginaCanais - 10;
        CanaisDAO dao = new CanaisDAO();
        //(currentPage, totalPages);
        btnNext.setEnabled(true);
        btnEnd.setEnabled(true);

        if (tamanho == 0) {
            btnPrev.setEnabled(false);
            btnStart.setEnabled(false);
        } else {
            btnPrev.setEnabled(true);
            btnEnd.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        // TODO add your handling code here:
        indicePaginaCanais = indicePaginaCanais - 10;
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();

        //(currentPage, totalPages);
        int index = (int) dao.getRowCount();
        int tamanho = indicePaginaCanais + 10;

        int resultado = index - tamanho;

        if (resultado < 10) {
            btnNext.setEnabled(false);
            btnEnd.setEnabled(false);
        }

        if (tamanho == 0) {
            btnPrev.setEnabled(false);
            btnStart.setEnabled(false);
        } else {
            btnPrev.setEnabled(true);
            btnStart.setEnabled(true);
        }
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(tamanho, 10);
        tbDados.setModel(pagina);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        indicePaginaCanais = indicePaginaCanais + 10;
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        CanaisDAO dao = new CanaisDAO();
        DefaultTableModel pagina = (DefaultTableModel) dao.fetchBySize(0, 10);
        tbDados.setModel(pagina);
        btnStart.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(true);
        btnEnd.setEnabled(true);
        indicePaginaCanais = 0;
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        // Botão atualizar tabela:
        atualizarTabela();
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    private void tbDadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDadosMousePressed

    private void tbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMouseClicked
        // TODO add your handling code here:
        if (tbDados.getSelectedRow() != -1) {
            txtNomeCanal.setText(tbDados.getValueAt(tbDados.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbDadosMouseClicked

    private void campoBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyTyped
        // TODO add your handling code here:
        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canais WHERE nome_canal LIKE ?";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, "%" + campoBusca.getText() + "%");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDados.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_canais"),
                    rs.getString("nome_canal"),
                    rs.getString("tipo_canal"),
                    rs.getString("padrao_autenticacao"),});
            }
            rs.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_campoBuscaKeyTyped

    private void campoBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaKeyPressed

    private void jTextField_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pesqActionPerformed

    private void btnAtualizarTabela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabela3ActionPerformed
        // TODO add your handling code here:
        atualizarTabelaUsu();
    }//GEN-LAST:event_btnAtualizarTabela3ActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(0, 10);

        tbDadosUsu.setModel(paginaUsu);
        btnStart2.setEnabled(false);
        btnPrev2.setEnabled(false);
        btnNext2.setEnabled(true);
        btnEnd2.setEnabled(true);
        indicePaginaUsuario = 0;
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext2MouseClicked
        // TODO add your handling code here:
        indicePaginaUsuario = indicePaginaUsuario + 10;
    }//GEN-LAST:event_btnNext2MouseClicked

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();

        //(currentPage, totalPages);
        int index = (int) daoUsu.getRowCountUsu();
        int tamanhoUsu = indicePaginaUsuario + 10;

        int resultado = index - tamanhoUsu;

        if (resultado < 10) {
            btnNext2.setEnabled(false);
            btnEnd2.setEnabled(false);
        }

        if (tamanhoUsu == 0) {
            btnPrev2.setEnabled(false);
            btnStart2.setEnabled(false);
        } else {
            btnPrev2.setEnabled(true);
            btnStart2.setEnabled(true);
        }
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(tamanhoUsu, 10);
        tbDadosUsu.setModel(paginaUsu);
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnPrev2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev2MouseClicked
        // TODO add your handling code here:
        indicePaginaUsuario = indicePaginaUsuario - 10;
    }//GEN-LAST:event_btnPrev2MouseClicked

    private void btnPrev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev2ActionPerformed
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        //(currentPage, totalPages);

        int tamanhoUsu = indicePaginaUsuario - 10;

        btnNext2.setEnabled(true);
        btnEnd2.setEnabled(true);

        if (tamanhoUsu == 0) {
            btnPrev2.setEnabled(false);
            btnStart2.setEnabled(false);
        } else {
            btnPrev2.setEnabled(true);
            btnStart2.setEnabled(true);
        }
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(tamanhoUsu, 10);
        tbDadosUsu.setModel(paginaUsu);
    }//GEN-LAST:event_btnPrev2ActionPerformed

    private void btnEnd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnd2ActionPerformed
        // TODO add your handling code here:
        UsuarioDAO daoUsu = new UsuarioDAO();
        int indexTbUsu = (int) daoUsu.getRowCountUsu();

        int valorfinal = indexTbUsu / 10;
        int valortotal = valorfinal * 10;
        System.out.println(valorfinal);
        DefaultTableModel paginaUsu = (DefaultTableModel) daoUsu.fetchBySizeUsu(valortotal, 10);
        tbDadosUsu.setModel(paginaUsu);
        btnNext2.setEnabled(false);
        btnEnd2.setEnabled(false);
        btnStart2.setEnabled(true);
        btnPrev2.setEnabled(true);
        indicePaginaUsuario = valortotal;
    }//GEN-LAST:event_btnEnd2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesAtivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoesAtivas().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelConfigAdm;
    private javax.swing.JPanel PainelConfigUser;
    private javax.swing.JPanel PainelTabelaAdm;
    private javax.swing.JPanel PainelTabelaUsers;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnAtualizarTabela3;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnEnd2;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext2;
    private javax.swing.JLabel btnPaginaCanais;
    private javax.swing.JLabel btnPaginaUsuario;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnPrev2;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStart2;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoBuscaUser;
    private javax.swing.JComboBox<String> cbPadraoAutenticacao;
    private javax.swing.JComboBox<String> cbTipoCanal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneTabelaUser;
    private javax.swing.JLabel lbBtnAdd;
    private javax.swing.JLabel lbBtnAddUser;
    private javax.swing.JLabel lbBtnEditar;
    private javax.swing.JLabel lbBtnEditarUser;
    private javax.swing.JLabel lbBtnExcluir;
    private javax.swing.JLabel lbBtnExcluirUser;
    private javax.swing.JLabel lbBtnPerfil;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailPefil;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCanal;
    private javax.swing.JLabel lbNomeUser;
    private javax.swing.JLabel lbPadraoAutenticacao;
    private javax.swing.JLabel lbPesquiUser1;
    private javax.swing.JLabel lbPesquiUser2;
    private javax.swing.JLabel lbSenhaUser;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTipoCanal;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelBotoesUser;
    private javax.swing.JPanel painelBtnAdd;
    private javax.swing.JPanel painelBtnAddUser;
    private javax.swing.JPanel painelBtnEditar;
    private javax.swing.JPanel painelBtnEditarUser;
    private javax.swing.JPanel painelBtnExcluir;
    private javax.swing.JPanel painelBtnExcluirUser;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelNaveg;
    private javax.swing.JPanel painelNaveg2;
    private javax.swing.JTable tbDados;
    private javax.swing.JTable tbDadosUsu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCanal;
    private javax.swing.JTextField txtNomeUser;
    private javax.swing.JTextField txtSenhaUser;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {

        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM canais LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tbDados.getModel();
            modelo.setNumRows(0);
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getInt("id_canais"),
                    rs.getString("nome_canal"),
                    rs.getString("tipo_canal"),
                    rs.getString("padrao_autenticacao")
                });
            }
            rs.close();
            connection.close();
            indicePaginaCanais = 0;
            btnStart.setEnabled(false);
            btnPrev.setEnabled(false);

            if (paginaInicial <= 10) {
                btnNext.setEnabled(false);
                btnEnd.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
                btnEnd.setEnabled(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void atualizarTabelaUsu() {

        try {
            ConexaoComBanco ccb = new ConexaoComBanco();
            Connection connection = ccb.getConnection();
            String sql = "SELECT * FROM usuario LIMIT 0,10";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbDadosUsu.getModel();
            model.setNumRows(0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_usuario"),
                    rs.getString("nome_usuario"),
                    rs.getString("email_usuario"),
                    rs.getString("senha_usuario"),});
            }
            rs.close();
            connection.close();
            indicePaginaCanais = 0;
            btnStart2.setEnabled(false);
            btnPrev2.setEnabled(false);
            if (paginaInicialUsu <= 10) {
                btnNext2.setEnabled(false);
                btnEnd2.setEnabled(false);
            } else {
                btnNext2.setEnabled(true);
                btnEnd2.setEnabled(true);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
